sis-berkeley-edu/calcentral

app/controllers/bootstrap_controller.rb, app/controllers/canvas_lti_controller.rb
https://jira.ets.berkeley.edu/jira/browse/CLC-7007
Happy Friday!
=> CLC-7007 Improve home page rendering

src/assets/templates/finaid_tc.html
https://jira.berkeley.edu/browse/SISRP-44982
Screenshot:
=> SISRP-44982 FA Terms and Conditions - improve error handling

app/controllers/bootstrap_controller.rb, app/controllers/canvas_lti_controller.rb
https://jira.berkeley.edu/browse/SISRP-45548
See #1 for Dev PR
=> [QA] SISRP-45548 Improve home page rendering

app/models/campus_solutions/student_resources.rb, spec/models/campus_solutions/student_resources_spec.rb
https://jira.berkeley.edu/browse/SISRP-45460
QA PR for #4
=> [QA] SISRP-45460 - Remove eform Links from Student Resources Card for Law Students

package-lock.json, package.json
https://jira.berkeley.edu/browse/SISRP-45563
=> SISRP-45563 - Update HighCharts library

package-lock.json, package.json
https://jira.berkeley.edu/browse/SISRP-45563
See DEV PR #6
=> [QA] SISRP-45563 - Update HighCharts library

src/assets/javascripts/angular/directives/finaidPermissionsDirective.js, src/assets/templates/directives/finaid_permissions.html, src/assets/templates/finaid_tc.html
https://jira.berkeley.edu/browse/SISRP-44982
Adds logic to bring user back to the Aid Year-specific page in My Finances from the Terms and Conditions page.
=> SISRP-44982 FA Terms and Conditions - returns to Aid Year page instead of My Finances

app/models/edo_oracle/queries.rb
https://jira.berkeley.edu/browse/SISRP-45581
=> SISRP-44581 - Fixes enrollment SQL to return current data

src/react/components/_academics/EnrollmentLinks/Add.js, src/react/components/_academics/EnrollmentLinks/ConcurrentDrop.js, src/react/components/_academics/EnrollmentLinks/ConcurrentOptions.js, src/react/components/_academics/EnrollmentLinks/Drop.js, src/react/components/_academics/EnrollmentLinks/EnrollmentLinks.js, src/react/components/_academics/EnrollmentLinks/Options.js, src/react/components/_academics/EnrollmentLinks/OptionsGradingEnd.js, src/react/components/_academics/EnrollmentLinks/Swap.js
https://jira.berkeley.edu/browse/SISRP-45822
Fix prop drilling issue that prevented links from being disabled
=> SISRP-45822 - Enrollment Actions Not Blocked with F06 Service Indicator

src/react/components/EnrollmentLinks/Add.js, src/react/components/EnrollmentLinks/ConcurrentDrop.js, src/react/components/EnrollmentLinks/ConcurrentOptions.js, src/react/components/EnrollmentLinks/Drop.js, src/react/components/EnrollmentLinks/EnrollmentLinks.js, src/react/components/EnrollmentLinks/Options.js, src/react/components/EnrollmentLinks/OptionsGradingEnd.js, src/react/components/EnrollmentLinks/Swap.js
https://jira.berkeley.edu/browse/SISRP-45822
See PR #15 in master
Fix prop drilling issue that prevented links from being disabled
=> [QA] SISRP-45822 - Enrollment Actions Not Blocked with F06 Service Indicator

Gemfile, Gemfile.lock
https://jira.berkeley.edu/browse/SISRP-42655
=> SISRP-42655: Update bootrap-sass

app/models/my_registrations/cancellation_non_payment_module.rb, app/models/my_registrations/registrations_module.rb, app/models/my_registrations/shared_helpers.rb, app/models/my_registrations/statuses.rb, spec/controllers/my_registrations_controller_spec.rb, spec/models/my_registrations/cancellation_non_payment_module_spec.rb, spec/models/my_registrations/shared_helpers_spec.rb, spec/models/my_registrations/statuses_spec.rb, src/assets/javascripts/angular/controllers/widgets/academicsStatusHoldsBlocksController.js
https://jira.berkeley.edu/browse/SISRP-39674
- updates comparison logic for multiple careers in a term
- adds more rspec testing
- attempted to make things a bit more readable by splitting up the code by functionality
- should give a boost in performance
=> SISRP-39674 - Grad + Law Student Registration Status shown as 'Not Enrolled' - DEV

src/assets/javascripts/angular/controllers/widgets/financesLinksController.js, src/assets/templates/widgets/finances_links.html
https://jira-secure.berkeley.edu/browse/SISRP-36810
Definitely need to refactor this card as a whole. Great candidate for refactor, not because it's a low-hanging fruit, but because it needs to be simplified.
=> SISRP-36810 - iGRAD - Add Link on My Finances Card: CLC-Dev

app/models/service_alerts/alert.rb, app/models/user/auth.rb, app/models/user/data.rb, app/models/user/oauth2_data.rb, app/models/user/recent_uid.rb, app/models/user/saved_uid.rb, app/models/user/stored_users.rb, config/database.yml, config/initializers/rails_admin.rb, config/settings.yml, config/settings/development.yml, db/migrate/20190201233542_oec_isf.rb, db/migrate/20190422180339_create_ps_uc_saved_uids.rb, db/postgres_oracle/create_oracle_tables.sql, db/postgres_oracle/postgres_oracle_insert_stmts.sql, db/schema.rb, lib/oracle_primary_helper.rb, spec/models/user/data_spec.rb, spec/models/user/oauth2_data_spec.rb, spec/models/user/stored_users_spec.rb
https://jira-secure.berkeley.edu/browse/SISRP-45788
=> SISRP-45788 - Migrate PostgreSQL tables from CalCentral PostgreSQL to Oracle

app/models/canvas/proxy.rb
https://jira-secure.berkeley.edu/browse/SISRP-39613
=> SISRP-39613 - Adds response code and body logger for Canvas proxies

spec/models/edo_oracle/student_spec.rb
Tests added and improved by Rishab Srivastava and Samir Naqvi. CS 169, CalCentral A.
- Added a Nil test when student_ID is nil
- Added an integration test which does not stub out `User::Identifiers.lookup_campus_solutions_id`
=> [CalCentral A] student_spec.rb

app/models/concerns/academic_roles.rb, app/models/degree_progress/my_undergrad_requirements.rb, config/settings.yml, spec/models/concerns/academic_roles_spec.rb, spec/models/degree_progress/my_undergrad_requirements_spec.rb, spec/models/my_academics/my_academic_roles_spec.rb
https://jira-secure.berkeley.edu/browse/SISRP-45875
=> SISRP-45875 - Update UGRD Degree Progress Card to show APR link for COE and CED students

config/deploy.rb
https://jira-secure.berkeley.edu/browse/SISRP-45788
=> SISRP-45788 - Disabling Rails migrations during deploy

src/assets/templates/academics_semester_classes.html, src/assets/templates/widgets/enrollment/adjust_enrolled.html, src/assets/templates/widgets/enrollment/adjust_waitlisted.html, src/assets/templates/widgets/enrollment/decide.html
https://jira-secure.berkeley.edu/browse/SISRP-45810
=> SISRP-45810 - Add Waitlist warning message during enrollment process - CLC Dev Option 3

src/assets/javascripts/angular/controllers/widgets/booklistController.js, src/assets/javascripts/angular/controllers/widgets/textbookController.js, src/assets/templates/academics_booklist.html, src/assets/templates/academics_classinfo.html
https://jira-secure.berkeley.edu/browse/SISRP-38418
=> SISRP-38418 - Book List/Textbooks card - provide link to Law booklist website where applicable

app/controllers/ping_controller.rb, app/models/canvas_csv/provide_course_site.rb, app/models/canvas_lti/egrades.rb, app/models/oec/api_task_wrapper.rb, lib/background_job.rb, spec/controllers/canvas_course_grade_export_controller_spec.rb, spec/controllers/ping_controller_spec.rb, spec/models/canvas_csv/provide_course_site_spec.rb, spec/models/oec/api_task_wrapper_spec.rb
https://jira.ets.berkeley.edu/jira/browse/CLC-6932
Work from ETS/CalCentral cherry picked for our benefit.
=> CLC-6932 Remove code for Torquebox Backgroundable

spec/models/cal_groups/group_delete_spec.rb
Tests added and improved by Rishab Srivastava and Samir Naqvi. CS 169, CalCentral A.
- Created a test for the case where `:success` is `nil`, and added an additional expectation to make sure the `result[:group]` associated was also `nil`.
- Created a test for the case where` :resultCode` is `nil`.
-  DRYed out and added specific tests that check if correct group data is returned based on fake JSON file
=> [CalCentral A] group_delete_spec.rb

app/controllers/loan_history_controller.rb
https://jira-secure.berkeley.edu/browse/SISRP-44898
=> SISRP-44898 - CLC - Is Loan History Using Delegate's ID?

src/assets/stylesheets/_alerts.scss
https://jira-secure.berkeley.edu/browse/SISRP-46201
=> SISRP-46201 - CalCentral: Alerts bar 'Learn More' link fails accessibility check

app/models/my_academics/graduation.rb, src/assets/stylesheets/_profile.scss, src/assets/templates/directives/expected_graduation_terms.html, src/react/components/_academics/StudentProfile/GenericGraduation.js
https://jira-secure.berkeley.edu/browse/SISRP-45181
=> SISRP-45181 - Graduation Checklist logic correction (UX Dev)

app/models/edo_oracle/financial_aid/queries.rb, spec/models/edo_oracle/financial_aid/queries_spec.rb, spec/models/financial_aid/my_aid_years_spec.rb
https://jira-secure.berkeley.edu/browse/SISRP-46226
=> SISRP-46226 - Aid Year Should Display Most Recent Year First if No Default Year

app/models/campus_solutions/student_resources.rb, spec/models/campus_solutions/student_resources_spec.rb
https://jira-secure.berkeley.edu/browse/SISRP-45190
=> SISRP-45190 - DCR Link in CalCentral Student Resources Card

src/react/stylesheets/_colors.scss, src/react/stylesheets/buttons.scss
https://jira-secure.berkeley.edu/browse/SISRP-46223
=> SISRP-46223 - Button Style Adjustment

src/react/components/_academics/StudentProfile/GenericGraduation.js, src/react/components/_academics/StudentProfile/StudentProfile.js
https://jira-secure.berkeley.edu/browse/SISRP-45745
https://jira.berkeley.edu/browse/SISRP-45745
=> SISRP-45745: Conflict bugfix

src/assets/templates/academics_semester_classes.html, src/assets/templates/widgets/enrollment/decide.html
https://jira-secure.berkeley.edu/browse/SISRP-45810
=> SISRP-45810 - Updates waitlisted units calculation verbage

app/controllers/my_law_awards_controller.rb, app/models/my_academics/law/awards.rb, app/models/my_academics/law/queries.rb, app/models/my_academics/law/transcript_notes.rb, config/routes.rb, src/assets/templates/academics.html, src/react/components/_academics/AcademicSummary/AcademicSummary.js, src/react/components/_academics/AcademicSummary/StudentProfile.js, src/react/components/_academics/StudentProfile/CollegeAndLevelError.js, src/react/components/_academics/StudentProfile/ConcurrentEnrollmentMessage.js, src/react/components/_academics/StudentProfile/GPAToggle.js, src/react/components/_academics/StudentProfile/LawAwards.js, src/react/components/_academics/StudentProfile/MissingPhoto.js, src/react/components/_academics/StudentProfile/MissingPhoto.scss, src/react/components/_academics/StudentProfile/NameAndPhoto.js, src/react/components/_academics/StudentProfile/ProfilePicture.js, src/react/components/_academics/StudentProfile/StatusAsOf.js, src/react/components/_academics/StudentProfile/StudentProfile.scss, src/react/components/_academics/StudentProfile/StudentProfileCard.js, src/react/components/_academics/StudentProfile/StudentProfileCard.scss, src/react/helpers/gpa.js, src/react/stylesheets/_colors.scss, src/react/stylesheets/_mixins.scss, src/react/stylesheets/_variables.scss, src/redux/actions/lawAwardsActions.js, src/redux/reducers/AppReducer.js, src/redux/reducers/LawAwardsReducer.js
https://jira-secure.berkeley.edu/browse/SISRP-44996
https://jira.berkeley.edu/browse/SISRP-44996
=> SISRP-44996: Display Law academic awards e.g. Juris/Prosser

app/models/my_academics/law/awards.rb, app/models/my_academics/law/queries.rb, app/models/my_academics/law/transcript_notes.rb
https://jira-secure.berkeley.edu/browse/SISRP-44996
=> SISRP-44996: Typo in method call bugfix

package-lock.json, package.json, webpack/base.config.js
https://jira-secure.berkeley.edu/browse/SISRP-45859
https://jira.berkeley.edu/browse/SISRP-45859
=> SISRP-45859 - CA Enrollment Ackn link doesn't show in IE/Firefox

src/react/components/_academics/StatusAndHoldsCard/RegistrationStatus.js
=> SISRP-39674 - Fixes display of summary with no explanation

src/assets/templates/user_overview.html, src/assets/templates/widgets/overview_status_and_holds.html
https://jira-secure.berkeley.edu/browse/SISRP-46462
https://jira.berkeley.edu/browse/SISRP-46462
=> SISRP-46462: Status & Holds card doesn't load on student overview page

src/react/components/_finances/BillingSummary/LearnMore.js, src/react/helpers/filters.js
https://jira-secure.berkeley.edu/browse/SISRP-45351
https://jira.berkeley.edu/browse/SISRP-45351
Verbiage updates and currency formatting
=> SISRP-45351: Phase A: SF CalCentral Enhancements

config/initializers/rails_admin.rb
https://jira-secure.berkeley.edu/browse/SISRP-44096 - fixed the issue related to searching by UID in rails admin
=> SISRP-44096: fixed searching by uid

src/react/components/_academics/StudentProfile/GenericGraduation.js, src/react/components/_academics/StudentProfile/UndergraduateGraduation.js
https://jira-secure.berkeley.edu/browse/SISRP-45755
=> SISRP-45755 - Updates Academic Profile card to display Terms in Attendance for UGRD students

src/react/components/_academics/StudentProfile/GenericGraduation.js, src/react/components/_academics/StudentProfile/StudentProfileCard.js, src/react/components/_academics/StudentProfile/UndergraduateGraduation.js
https://jira-secure.berkeley.edu/browse/SISRP-45181
=> SISRP-45181 - Fixes logic to display 'View Graduation Checklist' link

src/react/components/_academics/StudentProfile/GenericGraduation.js
https://jira-secure.berkeley.edu/browse/SISRP-45755
=> SISRP-45755: Don't display 'Terms in Attendance' label if data unavailable

app/models/financials/proxy.rb
https://jira-secure.berkeley.edu/browse/SISRP-46673
=> SISRP-46673 - Switch from digest auth to basic auth for CFV API v2

app/models/user/oauth2_data.rb, db/migrate/20190422180339_create_ps_uc_saved_uids.rb, db/schema.rb, spec/models/user/oauth2_data_spec.rb
https://jira-secure.berkeley.edu/browse/SISRP-44096
=> SISRP-44096 - Renames OAuth2 Token Expiration column

app/models/user/oauth2_data.rb, db/migrate/20190422180339_create_ps_uc_saved_uids.rb, db/schema.rb, spec/models/user/oauth2_data_spec.rb
https://jira-secure.berkeley.edu/browse/SISRP-44096
See DEV PR #85
=> [QA] SISRP-44096: rename oauth token expire column

src/react/components/_academics/StudentProfile/GenericGraduation.js
https://jira-secure.berkeley.edu/browse/SISRP-45755
See DEV PR #79
=> [QA] SISRP-45755: Don't display 'Terms in Attendance' label if data unavailable

src/react/components/_academics/StudentProfile/GenericGraduation.js, src/react/components/_academics/StudentProfile/StudentProfileCard.js, src/react/components/_academics/StudentProfile/UndergraduateGraduation.js
https://jira-secure.berkeley.edu/browse/SISRP-45181
See DEV PR #80
=> [QA] SISRP-45181 - Fixes logic to display 'View Graduation Checklist' link

package-lock.json, package.json
https://jira-secure.berkeley.edu/browse/SISRP-46731
=> SISRP-46731 - Updates Axios package in CalCentral

src/react/components/_academics/StatusAndHoldsCard/RegistrationPeriod.js
https://jira-secure.berkeley.edu/browse/SISRP-46735
=> SISRP-46735: Empty terms appearing in QAT Status and Holds card

src/react/components/_academics/StatusAndHoldsCard/RegistrationPeriod.js
https://jira-secure.berkeley.edu/browse/SISRP-46735
See #92 for DEV PR
=> [QA] SISRP-46735: Empty terms appearing in QAT Status and Holds card

src/react/components/_user_overview/EmploymentAppointments/EmploymentAppointments.js
https://jira-secure.berkeley.edu/browse/SISRP-42206
=> SISRP-42206: Add flatMap to fix IE bug in EmploymentAppointments

src/react/components/_academics/StatusAndHoldsCard/RegistrationPeriod.js
https://jira-secure.berkeley.edu/browse/SISRP-44837
=> SISRP-44837-bugfix: Always show semester with CalGrant Acknowledgement Status

src/react/components/_user_overview/EmploymentAppointments/EmploymentAppointments.js
https://jira-secure.berkeley.edu/browse/SISRP-42206
See #96 for DEV PR
=> [QA] SISRP-42206: Add flatMap to fix IE bug in EmploymentAppointments

config/settings.yml, src/react/components/_academics/StatusAndHoldsCard/CalGrantAcknowledgement/HoldListItem.js, src/react/components/_academics/StatusAndHoldsCard/CalGrantAcknowledgement/Status.js, src/react/components/_academics/StatusAndHoldsCard/CalGrantStatusItem.js, src/react/components/_academics/StatusAndHoldsCard/SemesterStatuses.js
https://jira-secure.berkeley.edu/browse/SISRP-45054
=> SISRP-45054: Put feature behind flag for release

config/settings.yml, src/react/components/_user_overview/EmploymentAppointments/EmploymentAppointments.js
https://jira-secure.berkeley.edu/browse/SISRP-42206
=> SISRP-42206: Put employment appointments behind feature flag

config/settings.yml, src/react/components/_academics/StatusAndHoldsCard/CalGrantAcknowledgement/HoldListItem.js, src/react/components/_academics/StatusAndHoldsCard/CalGrantAcknowledgement/Status.js, src/react/components/_academics/StatusAndHoldsCard/CalGrantStatusItem.js, src/react/components/_academics/StatusAndHoldsCard/SemesterStatuses.js
https://jira-secure.berkeley.edu/browse/SISRP-45054
DEV PR: #101
=> [QA] SISRP-45054: Put feature behind flag for release

config/settings.yml, src/react/components/_user_overview/EmploymentAppointments/EmploymentAppointments.js
https://jira-secure.berkeley.edu/browse/SISRP-42206
DEV PR: #104
=> [QA] SISRP-42206: Put employment appointments behind feature flag

app/models/financials/proxy.rb, config/settings.yml
https://jira-secure.berkeley.edu/browse/SISRP-46673
=> [QA] SISRP-46673 - Updates to support CFV API v2

src/assets/javascripts/angular/controllers/widgets/classInfoEnrollmentController.js
https://jira-secure.berkeley.edu/browse/SISRP-46835
=> SISRP-46835 - Faculty Enrollment List getting error in CalCentral, My Academics, Enrollment List

src/assets/javascripts/angular/controllers/widgets/classInfoEnrollmentController.js
https://jira-secure.berkeley.edu/browse/SISRP-46835
See Dev PR #109
=> [QA] SISRP-46835 - Faculty Enrollment List getting error in CalCentral, My Academics, Enrollment List

src/assets/javascripts/angular/factories/holdsFactory.js
https://jira-secure.berkeley.edu/browse/SISRP-46903
=> SISRP-46903: Active Holds not appearing on Advisor Student Overview

src/assets/javascripts/index.js, src/react/components/index.js
Allows us to add testing files in the tree without breaking the build
=> NOJIRA: Specify react components to import

src/assets/javascripts/angular/factories/transferCreditFactory.js
https://jira-secure.berkeley.edu/browse/SISRP-46868
=> SISRP-46868 - Transfer Credit card missing from CalCentral for advisors

src/assets/templates/widgets/academics/degree_progress_graduate.html
https://jira-secure.berkeley.edu/browse/SISRP-46744
=> SISRP-46744: CalCentral degree progress card, incorrect milestone info displayed

src/assets/javascripts/angular/factories/academicStandingsFactory.js
https://jira-secure.berkeley.edu/browse/SISRP-46868
=> SISRP-46868 - Fixes call for Student Overview Academic Standing

src/assets/javascripts/angular/factories/holdsFactory.js
https://jira-secure.berkeley.edu/browse/SISRP-46903
See dev PR #113
=> [QA] SISRP-46903: Active Holds not appearing on Advisor Student Overview

src/assets/javascripts/angular/factories/academicStandingsFactory.js, src/assets/javascripts/angular/factories/transferCreditFactory.js
https://jira-secure.berkeley.edu/browse/SISRP-46868
=> [QA] SISRP-46868 - Transfer Credit card missing from CalCentral for advisors

src/assets/templates/widgets/academics/degree_progress_graduate.html
https://jira-secure.berkeley.edu/browse/SISRP-46744
See DEV PR #116
=> [QA] SISRP-46744: CalCentral degree progress card, incorrect milestone info displayed

src/assets/templates/widgets/finaid_summary_netcost.html
https://jira-secure.berkeley.edu/browse/SISRP-41085
=> SISRP-41085: FA Summary Card - minor fix

src/assets/templates/academics_semesters.html, src/assets/templates/widgets/finaid/housing.html
https://jira-secure.berkeley.edu/browse/SISRP-46925
=> SISRP-46925: Add arrow to header links in Semester & Housing cards

app/controllers/campus_solutions/pnp_calculator_controller.rb, app/models/campus_solutions/message_catalog.rb, app/models/campus_solutions/my_financial_aid_funding_sources.rb, app/models/financial_aid/my_housing.rb, app/models/my_academics/class_enrollments.rb, app/models/my_academics/exams.rb, app/models/my_academics/graduation.rb, app/models/my_academics/merged.rb, app/models/my_academics/messages.rb, app/models/my_academics/my_standings.rb, spec/models/campus_solutions/message_catalog_spec.rb, spec/models/financial_aid/my_housing_spec.rb, spec/models/my_academics/class_enrollments_spec.rb, spec/models/my_academics/exams_spec.rb, spec/models/my_academics/messages_spec.rb, src/assets/javascripts/angular/factories/enrollmentFactory.js, src/assets/templates/academics_semester_classes.html, src/assets/templates/widgets/enrollment/decide.html
https://jira-secure.berkeley.edu/browse/SISRP-46690
=> SISRP-46690 - Update Waitlist warning message during enrollment process

app/controllers/campus_solutions/link_controller.rb
https://jira-secure.berkeley.edu/browse/SISRP-46798
=> SISRP-46798 - CLC Direct Deposit text not showing for delegates

app/models/hub_edos/user_attributes.rb, app/models/user/aggregated_attributes.rb, app/models/user/api.rb, app/models/user/has_student_history.rb, app/models/user/identifiers.rb, public/dummy/json/status.json, spec/models/user/aggregated_attributes_spec.rb, spec/models/user/api_spec.rb, spec/models/user/has_student_history_spec.rb, spec/models/user/identifiers_spec.rb, spec/ui_selenium/pages/api_my_status_page.rb
https://jira-secure.berkeley.edu/browse/SISRP-46907
=> SISRP-46907 - Removes deprecated legacy student identifier code

app/models/edo_oracle/queries.rb, app/models/edo_oracle/user_courses/base.rb, config/initializers/populate_sysadm_h2.rb, package-lock.json, package.json, spec/models/edo_oracle/queries_spec.rb, spec/models/edo_oracle/user_courses/base_spec.rb
https://jira-secure.berkeley.edu/browse/SISRP-46531
=> SISRP-46531 - Adds lapse date and display boolean to query in EdoOracle::Queries.get_enrolled_sections

src/react/components/_academics/AcademicSummary/PrimarySection.js
https://jira-secure.berkeley.edu/browse/SISRP-46280
=> SISRP-46280 - Enrollment that appears in Semesters Card doesn't appear in Academic Summary

app/controllers/advising_student_controller.rb, spec/controllers/advising_student_controller_spec.rb, src/assets/javascripts/angular/controllers/pages/userOverviewController.js, src/assets/templates/widgets/overview_status_and_holds.html
https://jira-secure.berkeley.edu/browse/SISRP-41637
=> SISRP-41637 - Show Student's Visa status to advisors in CalCentral

src/assets/stylesheets/_alerts.scss
https://jira-secure.berkeley.edu/browse/SISRP-46471
=> SISRP-46471 - CalCentral: Service Alerts Message Banner - CLC Dev

src/assets/templates/widgets/finaid_summary.html
https://jira-secure.berkeley.edu/browse/SISRP-41085
=> SISRP-41085 - restores View Awards button

app/models/edo_oracle/user_courses/base.rb, app/models/my_academics/student_links.rb, spec/models/edo_oracle/user_courses/base_spec.rb, spec/models/my_academics/student_links_spec.rb, src/assets/javascripts/angular/directives/academicSectionIncompleteGradingStatus.js, src/assets/stylesheets/_academics.scss, src/assets/templates/academics_final_grades.html, src/assets/templates/academics_semesters.html, src/assets/templates/directives/academic_section_incomplete_grading_status.html, src/react/components/CampusSolutionsLink/CampusSolutionsLinkContainer.js, src/react/components/_academics/AcademicSummary/PrimarySection.js, src/react/components/_academics/AcademicSummary/SectionIncompleteGradingStatus.js, src/react/components/_academics/AcademicSummary/SectionIncompleteGradingStatus.scss, src/react/components/_academics/AcademicSummary/SemesterSections.js
https://jira-secure.berkeley.edu/browse/SISRP-46531
=> SISRP-46531 - Improvements to Incomplete Grade Information in Cal Central - Student view

package-lock.json, package.json
https://jira-secure.berkeley.edu/browse/SISRP-47341
=> SISRP-47341 - Update Security Vulnerabilities in lodash

src/assets/stylesheets/_base.scss, src/assets/stylesheets/_offcanvas.scss, src/assets/stylesheets/_splash.scss, src/assets/templates/splash.html, src/index-main.html
https://jira-secure.berkeley.edu/browse/SISRP-46492
=> SISRP-46492 - CalCentral Login Splash page - refresh, simplify and remove old video content

src/assets/templates/widgets/finaid_summary.html
https://jira-secure.berkeley.edu/browse/SISRP-47391
=> SISRP-47391 - Adds GoogleAnalytics to View Awards button and link

.travis.yml, README.md
https://jira-secure.berkeley.edu/browse/SISRP-47571
I'm using this pull request to test the Travis build
=> SISRP-47571 - Fix for Travis CI build failures. Removes PostgreSQL setup instructions from README

app/models/user/finances/billing_item.rb, src/react/components/_finances/TransactionsCard/BillingItem/ChargeItem.js, src/react/components/_finances/TransactionsCard/types.js
=> SISRP-45389: Update billing item labels, charge item class name

.travis.yml, README.md
https://jira-secure.berkeley.edu/browse/SISRP-47571
See DEV PR #158
=> [QA] SISRP-47571 - Fix Travis build by uninstalling Bundler 2.0 and specifying OpenJDK 8

app/models/user/finances/billing_item.rb, src/react/components/_finances/TransactionsCard/BillingItem/ChargeItem.js, src/react/components/_finances/TransactionsCard/types.js
=> [QA] SISRP-45389: Update billing item labels, charge item class name

src/react/components/_academics/AcademicSummary/SemesterSections.js
https://jira-secure.berkeley.edu/browse/SISRP-47623
=> SISRP-47623 - CalCentral Academic Summary-> link going to blank screen

src/react/components/_academics/AcademicSummary/SemesterSections.js
https://jira-secure.berkeley.edu/browse/SISRP-47623
See DEV PR #166
=> [QA] SISRP-47623 - CalCentral Academic Summary-> link going to blank screen

app/controllers/user/finances/billing_items_controller.rb, app/models/notifications/sis_expiry_processor.rb, app/models/user/finances/cache_expiry.rb, app/models/user/finances/cached_payments.rb
=> SISRP-45389: Allow delegate access and expire transactions on ENF

app/controllers/user/finances/billing_items_controller.rb, app/models/notifications/sis_expiry_processor.rb, app/models/user/finances/cache_expiry.rb, app/models/user/finances/cached_payments.rb
=> [QA] SISRP-45389: Allow delegate access and expire transactions on ENF

src/react/components/_academics/AcademicSummary/SectionIncompleteGradingStatus.js
https://jira-secure.berkeley.edu/browse/SISRP-46531
See DEV PR #169
=> [QA] SISRP-46531 - Omits row when lapse date or frozen grade status not displayed

src/react/components/_academics/StatusAndHoldsCard/CNPWarning.js, src/react/components/_academics/StatusAndHoldsCard/RegistrationPeriod.js
https://jira-secure.berkeley.edu/browse/SISRP-47626
=> [QA] SISRP-47626-Missing-Cancel-For-Non-Payment

src/assets/javascripts/angular/controllers/pages/userOverviewController.js
https://jira-secure.berkeley.edu/browse/SISRP-47646
=> SISRP-47646 - Student Overview page show two Degree Progress Cards

src/assets/javascripts/angular/controllers/pages/userOverviewController.js
=> [QA] SISRP-47646 - Student Overview page show two Degree Progress Cards

src/react/components/_finances/TransactionsCard/BillingItem/ChargeStatus.js, src/react/components/_finances/TransactionsCard/BillingItem/ChargesPaid.scss
=> SISRP-45389: Put partially paid status on the next line

src/react/components/_finances/TransactionsCard/BillingItem/ChargeStatus.js, src/react/components/_finances/TransactionsCard/BillingItem/ChargesPaid.scss, src/react/components/_finances/TransactionsCard/chargeStatuses.js
=> [QA] SISRP-45389: Put partially paid status on the next line

src/react/components/_finances/TransactionsCard/chargeStatuses.js
=> SISRP-45389: Label for due items is "Due Now"

src/react/components/_academics/StatusAndHoldsCard/CNPWarning.js
https://jira-secure.berkeley.edu/browse/SISRP-47626
See DEV PR #179
=> [QA] SISRP-47626-Missing-Cancel-For-Non-Payment HTML rendition of mesg catalog

src/react/components/_academics/AcademicSummary/LawSection.js, src/react/components/_academics/AcademicSummary/PrimarySection.js, src/react/components/_academics/AcademicSummary/Semester.js, src/react/components/_academics/AcademicSummary/SemesterSections.js, src/react/components/_academics/AcademicSummary/Semesters.js
https://jira-secure.berkeley.edu/browse/SISRP-47602
=> SISRP-47602: Law Student Academic Summary bug fixes

src/react/components/_academics/AcademicSummary/LawSection.js, src/react/components/_academics/AcademicSummary/PrimarySection.js
https://jira-secure.berkeley.edu/browse/SISRP-47602
=> SISRP-47602: Show grades for law sections

src/react/components/_academics/AcademicSummary/LawSection.js, src/react/components/_academics/AcademicSummary/PrimarySection.js, src/react/components/_academics/AcademicSummary/Semester.js, src/react/components/_academics/AcademicSummary/SemesterSections.js, src/react/components/_academics/AcademicSummary/Semesters.js
https://jira-secure.berkeley.edu/browse/SISRP-47602
See DEV PR #184
=> [QA] SISRP-47602: Law Student Academic Summary bug fixes

app/models/edo_oracle/financial_aid/queries.rb, app/models/financial_aid/my_awards.rb, spec/models/financial_aid/my_awards_spec.rb, src/assets/javascripts/angular/controllers/widgets/finaid/finaidAwardsController.js, src/assets/templates/widgets/finaid_awards.html
https://jira-secure.berkeley.edu/browse/SISRP-47830
('Report Outside Resources' link was not showing if student did not have any existing Gift Aid)
('Convert to Work-Study' link was not showing if 'Reduce/Cancel Loans' like was not present too)
=> SISRP-47830 - Convert to Work Study and Report Outside Resources Links not showing on Award Card

app/models/edo_oracle/financial_aid/queries.rb, app/models/financial_aid/my_awards.rb, spec/models/financial_aid/my_awards_spec.rb, src/assets/javascripts/angular/controllers/widgets/finaid/finaidAwardsController.js, src/assets/templates/widgets/finaid_awards.html
=> [QA] SISRP-47830 - Award Card fixes

app/models/my_registrations/registrations_module.rb, src/react/components/_academics/StatusAndHoldsCard/RegistrationPeriod.js
Handle different cases Grad for Status and Holds
=> SISRP-47705-Grad-Law-Missing-Status-Hold

app/models/my_registrations/registrations_module.rb
fixed Hold and Statuses messages
=> SISRP-47705-Grad-Status-Hold-messages

app/models/my_registrations/registrations_module.rb
changed grad messages and expanded text
=> SISRP-47705-Grad-Status-Hold-messages wrong messages

app/models/my_registrations/registrations_module.rb, src/react/components/_academics/StatusAndHoldsCard/RegistrationPeriod.js
https://jira-secure.berkeley.edu/browse/SISRP-47705
=> [QA] SISRP-47705 grad law missing status hold

app/models/my_registrations/registrations_module.rb
=> [Qa] sisrp 47705 grad law missing status hold

src/react/components/_academics/EnrollmentLinks/Options.js
https://jira-secure.berkeley.edu/browse/SISRP-47968
=> SISRP-47968 - Options link isn't showing for law students

src/react/components/_academics/EnrollmentLinks/Options.js
https://jira-secure.berkeley.edu/browse/SISRP-47968
See DEV PR #199
=> [QA] SISRP-47968 - Options link isn't showing for law students

spec/models/financial_aid/my_awards_spec.rb, spec/models/hub_edos/proxy_spec.rb, src/assets/javascripts/angular/controllers/widgets/profile/basicNameController.js, src/assets/javascripts/angular/controllers/widgets/profile/basicPreferredNameController.js, src/assets/javascripts/angular/controllers/widgets/profile/demographicEthnicityController.js, src/assets/javascripts/angular/controllers/widgets/profile/demographicGenderController.js, src/assets/javascripts/angular/controllers/widgets/profile/demographicVeteranController.js, src/assets/javascripts/angular/controllers/widgets/profile/honorsAwardsSectionController.js, src/assets/javascripts/angular/services/profileService.js
https://jira-secure.berkeley.edu/browse/SISRP-46907
=> SISRP-46907 - Repairs loading of Profile data

public/maintenance/index_emergency.html, public/maintenance/index_maintenance.html, src/assets/templates/404.html, src/react/components/NotFound404.js
https://jira-secure.berkeley.edu/browse/SISRP-47831
=> SISRP-47831-404-contact-link

app/models/my_academics/advisor_links.rb, app/models/my_academics/filtered_for_advisor.rb, spec/models/my_academics/advisor_links_spec.rb, src/react/components/_academics/AcademicSummary/PrimarySection.js, src/react/components/_academics/AcademicSummary/SectionIncompleteGradingStatus.js, src/react/components/_academics/TransferCredit/TransferCredit.js
https://jira-secure.berkeley.edu/browse/SISRP-48032
=> SISRP-48032 - User is unable to see academic summaries in CalCentral

app/models/my_academics/advisor_links.rb, app/models/my_academics/filtered_for_advisor.rb, spec/models/my_academics/advisor_links_spec.rb, src/react/components/_academics/AcademicSummary/PrimarySection.js, src/react/components/_academics/AcademicSummary/SectionIncompleteGradingStatus.js, src/react/components/_academics/TransferCredit/TransferCredit.js
https://jira-secure.berkeley.edu/browse/SISRP-48032
See DEV PR #210
=> [QA] SISRP-48032 - User is unable to see academic summaries in CalCentral

src/redux/actions/profileActions.js
https://jira-secure.berkeley.edu/browse/SISRP-46907
=> SISRP-46907 - Fixes profile loading for Academic Summary Student Profile

src/react/components/APILink.js
https://jira-secure.berkeley.edu/browse/SISRP-48032
See DEV PR #215
=> [QA] SISRP-48032 - Fixes query string append in APIlink component

src/react/components/APILink.js
https://jira-secure.berkeley.edu/browse/SISRP-48032
See QA PR #214
=> SISRP-48032 - Fixes query string append in APIlink component

app/models/financial_aid/my_awards.rb, fixtures/xml/campus_solutions/link_api_multiple.xml, spec/models/financial_aid/my_financial_aid_summary_spec.rb, src/assets/javascripts/angular/controllers/widgets/finaid/finaidAwardsController.js, src/assets/templates/widgets/finaid_awards.html
https://jira-secure.berkeley.edu/browse/SISRP-47715
Limits appearance of the link to students and ex-students
=> SISRP-47715 - Fixes Fin Aid Summary link security on the Awards Card

app/models/financial_aid/my_awards.rb, src/assets/templates/widgets/finaid_awards.html
https://jira-secure.berkeley.edu/browse/SISRP-47715
=> SISRP-47715 - Fixes (#2) Fin Aid Summary link on Awards Card

app/controllers/campus_solutions/financial_resources_controller.rb, app/models/campus_solutions/financial_aid_summary_link.rb, config/routes.rb, src/assets/javascripts/angular/controllers/widgets/financesLinksController.js, src/assets/javascripts/angular/factories/financesLinksFactory.js, src/assets/templates/widgets/finances_links.html
https://jira-secure.berkeley.edu/browse/SISRP-48379
=> SISRP-48379 - Adds FA Summary link to Financial Resources card

Gemfile, Gemfile.lock, src/assets/javascripts/angular/services/authService.js, src/assets/javascripts/angular/services/userService.js, src/assets/templates/splash.html
https://jira-secure.berkeley.edu/browse/SISRP-46732
This update based on [Omniauth Wiki - Resolving CVE 2015 9284](https://github.com/omniauth/omniauth/wiki/Resolving-CVE-2015-9284)
=> SISRP-46732 - Address OmniAuth Ruby gem vulnerability

Gemfile, Gemfile.lock, src/assets/javascripts/angular/services/authService.js, src/assets/javascripts/angular/services/userService.js, src/assets/templates/splash.html
https://jira-secure.berkeley.edu/browse/SISRP-46732
Reverts sis-berkeley-edu/calcentral#222
=> Revert "SISRP-46732 - Address OmniAuth Ruby gem vulnerability"

src/assets/templates/widgets/academic_plan.html
https://jira-secure.berkeley.edu/browse/SISRP-46807
=> SISRP-46807 - Improvements to Incomplete Grade Information in Cal Central - Advisor View

app/models/my_academics/class_enrollments.rb, spec/models/my_academics/class_enrollments_spec.rb
https://jira-secure.berkeley.edu/browse/SISRP-47557
=> SISRP-47557 - Improve error handling in Class Enrollments model

app/models/concerns/academic_roles.rb, app/models/degree_progress/my_undergrad_requirements.rb, spec/models/concerns/academic_roles_spec.rb, spec/models/degree_progress/my_undergrad_requirements_spec.rb, spec/models/my_academics/my_academic_roles_spec.rb
https://jira-secure.berkeley.edu/browse/SISRP-46263
=> SISRP-46263 - Update UGRD Degree Progress Card to show APR link for UBUS students

src/assets/templates/widgets/finaid_awards.html
https://jira-secure.berkeley.edu/browse/SISRP-47715
=> SISRP-47715 - fixes FA Summary link on the Awards card

app/models/campus_solutions/financial_aid_summary_link.rb, app/models/financial_aid/my_awards.rb, fixtures/xml/campus_solutions/link_api_multiple.xml, spec/models/financial_aid/my_financial_aid_summary_spec.rb
https://jira-secure.berkeley.edu/browse/SISRP-47715
=> SISRP-47715 - Changes URL_ID for CS FA Summary fluid page

app/models/user/academics/calgrant_acknowledgement.rb, app/models/user/academics/calgrant_acknowledgements.rb, app/models/user/academics/calgrant_acknowledgements_cached.rb, app/models/user/academics/hold.rb, app/models/user/academics/holds.rb, app/models/user/academics/status/calgrant_acknowledgement.rb, app/models/user/academics/status/cancellation_for_non_payment.rb, app/models/user/academics/status/concurrent.rb, app/models/user/academics/status/messages.rb, app/models/user/academics/status/null_status.rb, app/models/user/academics/status/postgraduate.rb, app/models/user/academics/status/severity.rb, app/models/user/academics/status/undergraduate.rb, app/models/user/academics/student_attributes.rb, app/models/user/academics/term.rb, app/models/user/academics/term_registration.rb, app/models/user/current.rb, package.json, spec/models/user/academics/term_registration_spec.rb, src/react/components/_academics/StatusAndHoldsCard/CalGrantStatusItem.js, src/react/components/_academics/StatusAndHoldsCard/StatusItem.js, src/react/components/_academics/StatusAndHoldsCard/TermRegistrationStatus.js, src/react/components/_academics/StatusAndHoldsCard/TermRegistrationStatuses.js, src/react/components/_header/CNPStatusItem.js, src/react/components/_header/RegistrationStatusItem.js, src/react/components/_header/RegistrationStatusItemsForTerm.js, src/react/stylesheets/icons.scss, webpack/dev.config.js
https://jira-secure.berkeley.edu/browse/SISRP-46547
=> SISRP-46547 Et al., address remaining status and holds issues

app/models/my_academics/semesters.rb, spec/models/my_academics/semesters_spec.rb
=> SISRP-48320 - Fixes logic for Law Joint Degree students inactive in Law Career

src/assets/javascripts/angular/controllers/pages/academicsController.js
https://jira-secure.berkeley.edu/browse/SISRP-46547
=> SISRP-46547 Et al., always show status and holds card when there are term statuses to show

app/models/my_academics/college_and_level.rb, spec/models/my_academics/college_and_level_spec.rb, spec/support/spec_helper_module.rb, src/react/components/_academics/StudentProfile/Emphases.js, src/react/components/_academics/StudentProfile/Major.js, src/react/components/_academics/StudentProfile/Minor.js
https://jira-secure.berkeley.edu/browse/SISRP-48012
=> SISRP-48012 - Majors Displaying Incorrectly for Student

app/models/user/academics/status/postgraduate.rb
https://jira-secure.berkeley.edu/browse/SISRP-46547
=> SISRP-46547 Et al., remove limited access message from popover for postgrad careers

app/models/my_academics/semesters.rb, spec/models/my_academics/semesters_spec.rb
=> SISRP-48320 - Fixes issue with filtering enrollments

src/assets/javascripts/angular/controllers/widgets/finaid/finaidAwardsByTermController.js
https://jira-secure.berkeley.edu/browse/SISRP-47503
=> SISRP-47503 - Makes all values display cents when at least one value is not whole on the Awards by Term card

app/controllers/user_controller.rb, app/models/my_academics/my_academic_roles.rb, app/models/my_academics/semesters.rb, app/models/user/academics/student_groups.rb, app/models/user/academics/student_groups_cached.rb
This is expected to be reverted after we see more about what's happening in DEV and TST
=> SISRP-48320 - Adds logging for DEV/TST student group role issue

app/models/user/academics/queries.rb
=> SISRP-48320 - Adds more logging for DEV/TST student group role issue

app/controllers/user_controller.rb, app/models/my_academics/my_academic_roles.rb, app/models/my_academics/semesters.rb, app/models/user/academics/queries.rb, app/models/user/academics/student_groups.rb, app/models/user/academics/student_groups_cached.rb, spec/models/user/academics/student_groups_cached_spec.rb
* Reverts #242
* Reverts #243
* Adds fix for cacheing issue.
=> SISRP-48320 - Revert logs. Fix cacheing issue

src/assets/templates/widgets/finaid_awards_table_widget.html
https://jira-secure.berkeley.edu/browse/SISRP-47503
=> SISRP-47503 - Restores category title to Awards by Term card

src/assets/templates/widgets/finaid_awards_table_widget.html
https://jira-secure.berkeley.edu/browse/SISRP-47503
=> [QA] SISRP-47503 - Restores category title to Awards by Term card

app/models/user/finances/billing_item.rb, app/models/user/finances/billing_summary.rb
https://jira-secure.berkeley.edu/browse/SISRP-47722
=> SISRP-47722: Add Term Name, Transaction Number to CSV download

app/controllers/advising/academics/status_and_holds_controller.rb, app/models/user/academics/status/postgraduate.rb, config/routes.rb, spec/models/user/academics/status/postgraduate_spec.rb, spec/models/user/academics/status/undergraduate_spec.rb, src/assets/templates/widgets/overview_status_and_holds.html, src/assets/templates/widgets/status_and_holds.html, src/react/components/_academics/StatusAndHoldsCard/TermRegistrationStatuses.js, src/react/components/_academics/StatusAndHoldsCard/TermRegistrations.js, src/react/components/index.js, src/redux/actions/advisingStatusActions.js, src/redux/reducers/AdvisingReducer.js
=> SISRP-39674: Fixes to late reported issues

app/controllers/advising/academics/status_and_holds_controller.rb, app/models/user/academics/status/postgraduate.rb, config/routes.rb, spec/models/user/academics/status/postgraduate_spec.rb, spec/models/user/academics/status/undergraduate_spec.rb, src/assets/templates/widgets/overview_status_and_holds.html, src/assets/templates/widgets/status_and_holds.html, src/react/components/_academics/StatusAndHoldsCard/TermRegistrationStatuses.js, src/react/components/_academics/StatusAndHoldsCard/TermRegistrations.js, src/react/components/index.js, src/redux/actions/advisingStatusActions.js, src/redux/reducers/AdvisingReducer.js
=> [QA] SISRP-39674: Fixes to late reported issues

src/assets/javascripts/angular/controllers/pages/userOverviewController.js
https://jira-secure.berkeley.edu/browse/SISRP-48824
=> SISRP-48824: Advisors are not able to see VISA status on Status and Holds card

src/assets/javascripts/angular/controllers/widgets/holdsController.js
https://jira-secure.berkeley.edu/browse/SISRP-48788
=> SISRP-48788: CC-QA Status and Holds card shows blank contact info

src/assets/javascripts/angular/controllers/widgets/holdsController.js
https://jira-secure.berkeley.edu/browse/SISRP-48788
See DEV PR #257
=> [QA] SISRP-48788: CC-QA Status and Holds card shows blank contact info

src/assets/javascripts/angular/controllers/pages/userOverviewController.js
https://jira-secure.berkeley.edu/browse/SISRP-48824
See DEV PR #256
=> [QA] SISRP-48824: Advisors are not able to see VISA status on Status and Holds card

src/redux/reducers/AdvisingReducer.js
=> SISRP-39674: Clear advising student data when switching between students

src/redux/reducers/AdvisingReducer.js
=> [QA] SISRP-39674: Clear advising student data when switching between students

app/controllers/application_controller.rb, src/assets/javascripts/angular/calcentral.js
https://jira-secure.berkeley.edu/browse/SISRP-48831
=> SISRP-48831: Handle reauthentication during view-as in Angular

app/models/canvas/user_activity_stream.rb
https://jira-secure.berkeley.edu/browse/SISRP-48728
=> SISRP-48728 - bCourses Classes and Tasks for Dropped Classes Showing in CLC

spec/spec_helper.rb
=> NOJIRA - Prevent front-end scripts from running unneccesarily

app/models/hub_edos/student_api/v2/academic_statuses.rb, app/models/my_academics/college_and_level.rb, spec/models/my_academics/college_and_level_spec.rb
https://jira-secure.berkeley.edu/browse/SISRP-48835
=> SISRP-48835 - Graduated/non-active students and Advisors can no longer see GPA, Degrees Awarded, Career, and Level

app/models/user/academics/level.rb, app/models/user/academics/levels.rb, app/models/user/academics/registration.rb, spec/models/user/academics/level_spec.rb, spec/models/user/academics/levels_spec.rb
https://jira-secure.berkeley.edu/browse/SISRP-48920
=> SISRP-48920 - Refactoring preferred level logic

src/assets/javascripts/angular/controllers/pages/userOverviewController.js
https://jira-secure.berkeley.edu/browse/SISRP-48923
=> SISRP-48923 - Advisors cannot see Student Addresses, Phone Numbers or Emails

src/assets/templates/directives/academic_plans.html
https://jira-secure.berkeley.edu/browse/SISRP-48961
=> SISRP-48961 - Subplans/Concentrations are missing from Advisor Student Overview

src/react/components/_academics/AcademicSummary/SemesterSections.js
https://jira-secure.berkeley.edu/browse/SISRP-48956
=> SISRP-48956 - CalCentral Academic Summary only showing one section of course when student is enrolled in two sections

app/models/hub_edos/student_api/v2/academic_statuses.rb, app/models/my_academics/my_academic_status.rb, spec/models/hub_edos/student_api/v2/academic_statuses_spec.rb, spec/models/my_academics/my_academic_status_spec.rb
https://jira-secure.berkeley.edu/browse/SISRP-48835
=> SISRP-488335 - Updates MyAcademics::MyAcademicStatuses to fallback on inactive/completed program data when active program data not present

src/assets/javascripts/angular/controllers/pages/userOverviewController.js
=> [QA] SISRP-48923 - Advisors cannot see Student Addresses, Phone Numbers or Emails

src/assets/templates/directives/academic_plans.html
=> [QA] SISRP-48961 - Subplans/Concentrations are missing from Advisor Student Overview

app/models/concerns/academic_roles.rb, app/models/degree_progress/my_undergrad_requirements.rb, config/settings.yml, spec/models/concerns/academic_roles_spec.rb, spec/models/degree_progress/my_undergrad_requirements_spec.rb, spec/models/my_academics/my_academic_roles_spec.rb
https://jira-secure.berkeley.edu/browse/SISRP-47618
=> SISRP-47618 - Update UGRD Degree Progress Card to show APR link for UCNR students

app/models/edo_oracle/financial_aid/queries.rb
https://jira-secure.berkeley.edu/browse/SISRP-48286
=> SISRP-48286 Change source of Awards card messages

src/assets/templates/widgets/profile_popover.html
https://jira-secure.berkeley.edu/browse/SISRP-49119
=> SISRP-49119 - “Try the New Profile” link should only show to current students

src/assets/stylesheets/_sidebar.scss, src/assets/templates/widgets/loan_history/cumulative_loan_debt_card.html, src/assets/templates/widgets/loan_history/loan_summary_by_aid_year_card.html
https://jira-secure.berkeley.edu/browse/SISRP-49128
=> SISRP-49218 - Fixes header bar arrows on Loan History/Cumulative Summary Cards; Improves contrast on Profile sidebar

src/react/components/_finances/FinancialResources/FinancialResources.scss, src/react/components/_finances/FinancialResources/HasAccessTo.js
=> SISRP-47714 - Addresses feedback from Financial Resources testing

src/assets/templates/widgets/loan_history/cumulative_loan_debt_card.html, src/assets/templates/widgets/loan_history/loan_summary_by_aid_year_card.html
https://jira-secure.berkeley.edu/browse/SISRP-49128
=> SISRP-49128 - Fixes font size and corrects error in semantics

src/assets/templates/academics.html
https://jira-secure.berkeley.edu/browse/SISRP-48098
=> SISRP-48098 - Applicants need to see HOLDs in CalCentral

src/react/components/ButtonGroup.scss, src/react/components/DisclosureItem.scss, src/react/components/Tabs.scss, src/react/components/_finances/TransactionsCard/Badges/Badges.scss, src/react/components/_finances/TransactionsCard/BillingItem/BillingItem.scss, src/react/components/_finances/TransactionsCard/BillingItem/ChargeItem.scss, src/react/components/_finances/TransactionsCard/BillingItem/ChargesPaid.scss, src/react/components/_finances/TransactionsCard/BillingItem/ItemAdjustment.scss, src/react/components/_finances/TransactionsCard/BillingItem/ItemPayment.scss, src/react/components/_finances/TransactionsCard/BillingItem/ItemUpdated.scss, src/react/components/_finances/TransactionsCard/BillingItem/TransactionHistory.scss, src/react/components/_finances/TransactionsCard/BillingItemsTable/BillingItemsHeaders.scss, src/react/components/_finances/TransactionsCard/BillingItemsTable/ShowMore.scss, src/react/components/_finances/TransactionsCard/Filters/BillingItemSearch.scss, src/react/components/_finances/TransactionsCard/Filters/Dropdown.scss, src/react/components/_finances/TransactionsCard/TransactionsCard.scss, src/react/components/_finances/TransactionsCard/billing-items-grid.scss, src/react/components/_user_overview/EmploymentAppointments/AppointmentsTable.scss, src/react/components/_user_overview/EmploymentAppointments/InstructingAppointments.scss, src/react/stylesheets/_colors.scss, src/react/stylesheets/_foundation_overrides.scss, src/react/stylesheets/_variables.scss
https://jira-secure.berkeley.edu/browse/SISRP-48868
This ticket replaces the hex RGB code with well-known names. It also consolidates similar colors such as curious-blue and curious-blue-2
=> SISRP-48868 react button color maintenance

src/react/components/_finances/FinancialResources/HasAccessTo.js
=> SISRP-47714 - fixes error preventing iGrad link from displaying

src/assets/javascripts/angular/controllers/pages/enrollmentVerificationController.js, src/assets/templates/widgets/academics/enrollment_verification.html
https://jira-secure.berkeley.edu/browse/SISRP-48423
=> SISRP-48423 - fixes Enrollment Verification after returning from Campus Solutions

src/react/components/ReduxProvider.js, src/react/components/_academics/EnrollmentLinks/EnrollmentLinks.js
=> SISRP-47714 - adds redux provider to EnrollmentLinks

src/assets/javascripts/angular/services/widgetService.js, src/assets/templates/widgets/finaid_awards_section.html
https://jira-secure.berkeley.edu/browse/SISRP-47348
=> SISRP-47348 - Award Card updates

app/models/campus_solutions/student_resources.rb, spec/models/campus_solutions/student_resources_spec.rb
https://jira-secure.berkeley.edu/browse/SISRP-48341
=> SISRP-48341 - CPP - Add the Grad CPP eform link to Calcentral

src/react/components/APILink.js
https://jira-secure.berkeley.edu/browse/SISRP-49222
=> SISRP-49222 - APILink opens external URL in new tab fix

src/react/components/_finances/FinancialResources/HasAccessTo.js
=> SISRP-47714 - Financial Resources FA link access updates

src/react/components/_finances/FinancialResources/HasAccessTo.js
=> SISRP-47714 - Financial Resources FA link access updates 2

app/models/degree_progress/graduate_milestones.rb
https://jira-secure.berkeley.edu/browse/SISRP-49216
=> SISRP-49216 - Degree Progress Card not loading on Student Overview Page

src/assets/templates/widgets/academics/degree_progress_graduate.html
https://jira-secure.berkeley.edu/browse/SISRP-47731
=> SISRP-47731 - Updates labeling

app/models/degree_progress/my_undergrad_requirements.rb, spec/models/degree_progress/my_undergrad_requirements_spec.rb
https://jira-secure.berkeley.edu/browse/SISRP-48130
=> SISRP-48130 - Allow APR Link to Remain Active after Students' Last Day of Term for Expected Grad Term

src/react/components/_finances/FinancialResources/FinancialResources.js
=> SISRP-47714 - Financial Resources fixes delegate access

lib/services/background_jobs_check.rb, lib/services/jms_worker.rb
https://jira-secure.berkeley.edu/browse/SISRP-49281
=> SISRP-49281 - Prevent database connection leaks with background threads

app/models/campus_solutions/enrollment_term_expiry.rb
https://jira-secure.berkeley.edu/browse/SISRP-49279
=> SISRP-49279 - Semesters Card not updated in CalCentral after student enrollment

app/models/campus_solutions/user_api_expiry.rb
https://jira-secure.berkeley.edu/browse/SISRP-49279
These were originally missing from SISRP-46907, but this task reminded me to check to see if I forgot any models.
=> SISRP-49279 - Updates CampusSolutions::UserApiExpiry to include additional iHub cacheing models

src/assets/javascripts/angular/services/widgetService.js, src/assets/templates/widgets/finaid_awards_section.html
https://jira-secure.berkeley.edu/browse/SISRP-47348
=> SISRP-47348 - Changes appearance of Est. Disbursements disclosure button on Awards Card

src/assets/templates/widgets/finaid_awards_section.html
https://jira-secure.berkeley.edu/browse/SISRP-47348
=> SISRP-47348 - Corrects issues with disclosure icon on Awards Card

app/models/my_academics/semesters.rb
https://jira-secure.berkeley.edu/browse/SISRP-49357
=> SISRP-49357 - Student cannot see Semesters card on My Academics page

public/json/campuslinks.json
https://jira-secure.berkeley.edu/browse/SISRP-49280
=> SISRP-49280 - In CC-SIS-TEST Faculty can see page not found message for few My Campus links 

src/react/components/_finances/FinancialResources/FinancialResources.scss, src/react/components/_finances/FinancialResources/HasAccessTo.js, src/react/components/_finances/FinancialResources/WithAccess.js
=> SISRP-47714 - fixes spacing and allows applicants/exStudents to see links

src/react/components/_finances/FinancialResources/HasAccessTo.js
=> SISRP-47714 - Fixes issue with links for delegates on Financial Resources card

src/react/components/_finances/FinancialResources/HasAccessTo.js
=> SISRP-47714 - Emergency Loan links displayed only to registered students

app/models/berkeley/terms.rb, app/models/user/academics/degree_progress/graduate/candidacy_term_status.rb, spec/models/berkeley/terms_spec.rb, spec/models/user/academics/degree_progress/graduate/candidacy_term_status_spec.rb
https://jira-secure.berkeley.edu/browse/SISRP-47731
=> SISRP-47731 - Use term ID to display name method in Grad Degree Progress Card

app/models/my_academics/college_and_level.rb
https://jira-secure.berkeley.edu/browse/SISRP-49129
=> SISRP-49129 - Degree not appearing in CalCentral for student

src/assets/javascripts/angular/controllers/widgets/finaid/finaidAwardsController.js, src/assets/templates/widgets/finaid_awards.html, src/react/components/_finances/FinancialResources/HasAccessTo.js
=> SISRP-47714 - Prevents Applicants from seeing Financial Aid Summary Report link

src/react/components/_finances/FinancialResources/HasAccessTo.js
=> SISRP-47714 - Applicants should not see FPP links on Financial Resources

src/react/components/_finances/FinancialResources/HasAccessTo.js
=> [QA] SISRP-47714 - Applicants should not see FPP links on Financial Resources

app/models/concerns/academics_module.rb, app/models/my_academics/semesters.rb
https://jira-secure.berkeley.edu/browse/SISRP-49155
=> SISRP-49155 - Law Requirement Designations Missing in Academic Summary

app/models/concerns/academics_module.rb, app/models/my_academics/semesters.rb
https://jira-secure.berkeley.edu/browse/SISRP-49155
See DEV PR #336
=> [QA] SISRP-49155 - Law Requirement Designations Missing in Academic Summary

src/react/components/_finances/FinancialResources/HasAccessTo.js
=> SISRP-47714 - Fixes access to iGrad link

src/react/components/_finances/FinancialResources/FinaidFormsInfo.js
=> SISRP-47714: Remove redundant link

src/react/components/_finances/FinancialResources/FinaidFormsInfo.js
=> [QA] SISRP-47714: Remove redundant link

src/assets/templates/widgets/enrollment/notifications.html
https://jira-secure.berkeley.edu/browse/SISRP-49919
=> SISRP-49919 - Update Class Enrollment Card for LL.M./J.S.D. students

src/react/components/_finances/FinancialResources/HasAccessTo.js
https://jira-secure.berkeley.edu/browse/SISRP-50051
=> SISRP-50051 - removes excluding programs from hiding links on the Financial Resources card

src/assets/stylesheets/_header.scss, src/assets/templates/widgets/gear_popover.html, src/assets/templates/widgets/sir/sir_item_completed.html
https://jira-secure.berkeley.edu/browse/SISRP-48170
=> SISRP-48170 - Display EMPLID on New Admit Card

src/assets/templates/widgets/my_classes.html
https://jira-secure.berkeley.edu/browse/SISRP-40242
=> SISRP-40242- New Admit - Misleading prompt to visit My Academics

src/react/components/_finances/FinancialResources/HasAccessTo.js
https://jira-secure.berkeley.edu/browse/SISRP-50051
=> SISRP-50051 - removes excluding programs from Financial Resources card

app/models/campus_solutions/new_admit_resources.rb, spec/models/campus_solutions/new_admit_resources_spec.rb
https://jira-secure.berkeley.edu/browse/SISRP-48166
=> SISRP-48166 - Display NSS Dates and Deadlines to new admits in CalCentral

app/controllers/sessions_controller.rb, src/assets/templates/uid_slate_error.html
https://jira-secure.berkeley.edu/browse/SISRP-48134
=> SISRP-48134 - User Experience Issues - Using SSO from MAP to CC after Creating CalNet

app/models/campus_solutions/sir/sir_statuses.rb, src/assets/templates/widgets/sir/sir_item_completed.html
SISRP-46663 Confirming Deposit Waivers, before and after SIR (CLC DEV)
=> SISRP-46663 Confirming Deposit Waivers, before and after SIR (CLC DEV)

src/assets/templates/widgets/enrollment/notifications.html
=> [QA] SISRP-49919 - Update Class Enrollment Card for LL.M./J.S.D. students

src/assets/javascripts/angular/controllers/widgets/finaid/finaidAwardsController.js, src/assets/javascripts/angular/controllers/widgets/finaid/shouldShowDecimals.js
https://jira-secure.berkeley.edu/browse/SISRP-50258
=> SISRP-50258 - Fixes issue on Award Card that prevents some students from seeing My Financial Summary link

src/assets/templates/widgets/my_classes.html
https://jira-secure.berkeley.edu/browse/SISRP-40242
=> SISRP-40242 - New Admit - Misleading prompt to visit My Academics

src/assets/javascripts/angular/controllers/widgets/finaid/finaidAwardsController.js, src/assets/javascripts/angular/controllers/widgets/finaid/shouldShowDecimals.js
https://jira-secure.berkeley.edu/browse/SISRP-50258
=> [QA] SISRP-50258 - Fixes issue on Award Card that prevents some students from seeing My Financial Summary link

app/models/campus_solutions/sir/sir_statuses.rb, src/assets/templates/widgets/sir/sir_item_completed.html
https://jira-secure.berkeley.edu/browse/SISRP-46663
=> [QA] sisrp 46663 sir deposit waiver

app/models/campus_solutions/new_admit_resources.rb, spec/models/campus_solutions/new_admit_resources_spec.rb
=> [QA] SISRP-48166 - Display NSS Dates and Deadlines to new admits in CalCentral

src/assets/stylesheets/_header.scss, src/assets/templates/widgets/gear_popover.html, src/assets/templates/widgets/sir/sir_item_completed.html
=> [QA] SISRP-48170 - Display EMPLID on New Admit Card

src/assets/templates/uid_slate_error.html
=> [QA] SISRP-48134 - User Experience Issues - Using SSO from MAP to CC after Creating CalNet

src/assets/templates/widgets/my_classes.html
=> [QA] SISRP-40242 - New Admit - Misleading prompt to visit My Academics

app/models/user/tasks/completed_agreement.rb, app/models/user/tasks/queries.rb
=> SISRP-45818: Allow updates after expiration for completed tasks

app/models/user/tasks/incomplete_agreement.rb
=> SISRP-48518: Fix for undefined aid-year

app/models/financial_aid/my_awards.rb, app/models/user/affiliation.rb, app/models/user/affiliations.rb, app/models/user/current.rb, src/assets/javascripts/angular/controllers/widgets/finaid/finaidAwardsController.js
https://jira-secure.berkeley.edu/browse/SISRP-50258
=> SISRP-50258 - Updates Awards Card FinAid Summary link access to match Financial Resources

src/assets/templates/widgets/gear_popover.html
https://jira-secure.berkeley.edu/browse/SISRP-48170
=> SISRP-48170 - Display EMPLID via Profile pop up

src/assets/templates/widgets/gear_popover.html
=> [QA] SISRP-48170 - Display EMPLID via Profile pop up

app/models/financial_aid/my_awards.rb, app/models/user/affiliation.rb, app/models/user/affiliations.rb, app/models/user/current.rb, src/assets/javascripts/angular/controllers/widgets/finaid/finaidAwardsController.js
https://jira-secure.berkeley.edu/browse/SISRP-50258
DEV PR: https://github.com/sis-berkeley-edu/calcentral/pull/383/
=> [QA] SISRP-50258 - Updates Awards Card FinAid Summary link access to match Financial Resources

app/models/user/tasks/checklist_item.rb, app/models/user/tasks/completed_agreement.rb, app/models/user/tasks/completed_checklist_item.rb, app/models/user/tasks/incomplete_checklist_item.rb, app/models/user/tasks/queries.rb, src/react/components/_dashboard/NotificationsCard/ArchiveLink.js, src/react/components/_dashboard/NotificationsCard/CompactNotification.js, src/react/components/_dashboard/TasksCard/CompletedTasks/ByCategory.js, src/react/components/_dashboard/TasksCard/TaskDetail.js, src/react/components/_dashboard/TasksCard/tasks.module.js
=> SISRP-48518: Task sorting fixes

app/models/user/tasks/incomplete_checklist_item.rb, app/models/user/tasks/queries.rb
=> SISRP-48518: task query fix

src/react/components/_finances/FinancialResources/FinancialResources.js
https://jira-secure.berkeley.edu/browse/SISRP-50288
Note - we will need to revisit this in an upcoming sprint.  FASO wants Delegates to be able to view the Summer Aid Estimator link on the Financial Resources card, however this link depends on SIR data for the student.  Currently, delegates get a 403 response from the SIR api.
=> SISRP-50288 - Allows delegates to see the Financial Resources card

src/assets/javascripts/angular/controllers/pages/userOverviewController.js, src/assets/templates/widgets/toolbox/user_preview.html
https://jira-secure.berkeley.edu/browse/SISRP-49354
=> SISRP-49354 - Former Student's SID not appearing in CalCentral Student Overview

app/models/user/academics/student_attribute.rb, app/models/user/academics/term_registration.rb, src/assets/javascripts/angular/controllers/widgets/enrollment/enrollmentCardController.js, src/assets/templates/widgets/enrollment/adjust_enrolled.html, src/assets/templates/widgets/enrollment_card.html, src/react/components/_academics/EnrollmentLinks/EnrollmentLinks.js
Update Enrollment Card to source CalGrant Acknowledgement status from
Service Indicators rather than Activity Guides.
https://jira-secure.berkeley.edu/browse/SISRP-46622
=> SISRP-46622: FA Retrofit

src/assets/javascripts/angular/controllers/widgets/finaid/finaidSummaryController.js, src/assets/templates/widgets/finaid_communications.html, src/assets/templates/widgets/finaid_communications_tasks.html, src/assets/templates/widgets/finaid_summary.html, src/react/components/_finances/AidYearTaskCount.js, src/react/components/_finances/FinancialAidTasks.js, src/react/components/index.js
Get “incomplete financial aid tasks” count from new tasks card data sources
https://jira-secure.berkeley.edu/browse/SISRP-49978
=> SISRP-49978: Tasks Card - Keep FA cards in sync

app/models/user/tasks/notification.rb, app/models/user/tasks/queries.rb, src/assets/templates/widgets/finaid_communications.html, src/react/components/WidgetSubtitle.js, src/react/components/_dashboard/NotificationsCard/MessagesBySource.js, src/react/components/_dashboard/NotificationsCard/NoMessages.js, src/react/components/_dashboard/NotificationsCard/NotificationsCard.js, src/react/components/_dashboard/NotificationsCard/notifications.module.js, src/react/components/_finances/FinancialAidMessages.js, src/react/components/index.js
https://jira-secure.berkeley.edu/browse/SISRP-49978
=> SISRP-49978: List notifications on aid year page

src/react/components/_dashboard/TasksCard/Switcher.js, src/react/components/_finances/AidYearTaskCount.js
https://jira-secure.berkeley.edu/browse/SISRP-49978
=> SISRP-49978: Fix incomplete tasks count

app/controllers/concerns/advising_resources.rb, fixtures/xml/campus_solutions/link_api_multiple.xml
https://jira-secure.berkeley.edu/browse/SISRP-48981
=> SISRP-48981 - Update Link API ID reference for Advising Resources Card

src/react/components/_dashboard/NotificationsCard/NotificationsCard.js
=> SISRP-50100: Show all the messages, not just notifications

app/models/user/b_courses/todo.rb, app/models/user/tasks/incomplete_checklist_item.rb, app/models/user/tasks/queries.rb
=> SISRP-48518: Little fixes

src/react/components/_finances/FinancialResources/FinancialResources.js
https://jira-secure.berkeley.edu/browse/SISRP-50288
DEV PR: https://github.com/sis-berkeley-edu/calcentral/pull/387
=> [QA] SISRP-50288 - Allows delegates to see the Financial Resources card

app/models/campus_solutions/student_resources.rb, spec/models/campus_solutions/student_resources_spec.rb
https://jira-secure.berkeley.edu/browse/SISRP-49559
=> SISRP-49559 - Graduate Division Dissertation Signature eForm

app/models/user/tasks/incomplete_agreement.rb
=> SISRP-48518: fixed status date

app/models/campus_solutions/new_admit_resources.rb
https://jira-secure.berkeley.edu/browse/SISRP-48918
=> SISRP-48918- Withdrawal Link/Form is Confusing - Accidental Withdrawals

src/react/components/_finances/FinancialResources/HasAccessTo.js
https://jira-secure.berkeley.edu/browse/SISRP-50413
=> SISRP-50413 - Delegate Financial Services links missing

app/models/berkeley/user_roles.rb, src/assets/javascripts/angular/controllers/pages/academicsController.js, src/assets/templates/academics.html, src/assets/templates/withdrawn_admit.html
https://jira-secure.berkeley.edu/browse/SISRP-48144
=> SISRP-48144 - Withdrawn Admits - Experience in CalCentral

package-lock.json, package.json
=> SISRP-50100: Update react-linkify with version that actually works

app/models/campus_solutions/student_resources.rb, spec/models/campus_solutions/student_resources_spec.rb
https://jira-secure.berkeley.edu/browse/SISRP-49286
=> SISRP-49286 - eForm for Self-Service Expected Grad Term (EGT)

app/models/user/b_courses/todo.rb, src/react/components/_academics/StudentProfile/Degrees.js, src/react/components/_dashboard/NotificationsCard/ActionLink.js, src/react/components/_dashboard/TasksCard/OverdueTasks/index.js, src/react/useFocus.js
https://jira-secure.berkeley.edu/browse/SISRP-48151
=> SISRP-50100, 48518, 48151: Tasks notifications fixes

app/controllers/application_controller.rb, app/controllers/sessions_controller.rb, app/models/berkeley/user_roles.rb, app/models/user/authentication_validator.rb
https://jira-secure.berkeley.edu/browse/SISRP-50465
=> SISRP-50465 - New Admit Blocked From Logging Into CLC W/O SIR

src/assets/templates/widgets/finaid_awards.html, src/assets/templates/widgets/finaid_coa.html
https://jira-secure.berkeley.edu/browse/SISRP-50496
=> SISRP-50496 - Display messages using HTML on FA Awards and COA cards

src/assets/templates/widgets/finaid_awards.html, src/assets/templates/widgets/finaid_coa.html
https://jira-secure.berkeley.edu/browse/SISRP-50496
DEV PR: https://github.com/sis-berkeley-edu/calcentral/pull/411
=> [QA] SISRP-50496 - Display messages using HTML on FA Awards and COA cards

src/react/components/_finances/TransactionsCard/BillingItem/ItemAdjustment.js, src/react/components/_finances/TransactionsCard/BillingItem/ItemPayment.js, src/react/components/_finances/TransactionsCard/BillingItem/ItemUpdated.js, src/react/components/_finances/TransactionsCard/BillingItem/TransactionHistory.js, src/react/components/_finances/TransactionsCard/BillingItemsTable/BillingItemsTable.js, src/react/components/_finances/TransactionsCard/TransactionsCard.js, src/redux/actions/billingActions.js, src/redux/actions/lawAwardsActions.js, src/redux/reducers/BillingItemsReducer.js, src/redux/reducers/LawAwardsReducer.js
https://jira-secure.berkeley.edu/browse/SISRP-50491
=> SISRP-48518: Fixes transactions issues due to date-fns upgrade

app/models/user/b_courses/activity.rb, app/models/user/b_courses/todo.rb, app/models/user/current.rb, app/models/user/tasks/notifications.rb, app/models/user/webcasts/concern.rb, app/models/user/webcasts/webcast.rb, app/models/user/webcasts/webcasts.rb, src/react/components/_dashboard/NotificationsCard/ActionLink.js, src/react/components/_dashboard/NotificationsCard/CompactNotification.js, src/react/components/_dashboard/NotificationsCard/MessageDetail.js, src/react/components/_dashboard/NotificationsCard/NotificationsCard.js, src/react/components/_dashboard/TasksCard/IncompleteTasks/BCoursesTask.js, src/react/components/_dashboard/TasksCard/IncompleteTasks/CategoryHeader.js, src/react/components/_dashboard/TasksCard/IncompleteTasks/IncompleteDueSoonBadges.js
=> SISRP-50100: Notifications card test fixes

app/models/user/tasks/completed_agreement.rb, app/models/user/tasks/queries.rb, src/react/components/_finances/FinancialAidTasks.js
=> SISRP-50100 - add completed agreements to finaid communications card

app/models/user/b_courses/activities.rb, app/models/user/b_courses/events.rb, app/models/user/b_courses/todos.rb
https://jira-secure.berkeley.edu/browse/SISRP-50500
=> SISRP-50500: Handle empty bcourses responses

src/assets/templates/widgets/finaid_awards_term_widget.html
https://jira-secure.berkeley.edu/browse/SISRP-50496
=> SISRP-50496 - Allows HTML in message on Awards by Term card

src/react/components/_dashboard/NotificationsCard/MessagesBySource.js, src/react/components/_dashboard/NotificationsCard/NoMessages.js, src/react/components/_dashboard/NotificationsCard/NotificationsCard.js, src/react/components/_dashboard/NotificationsCard/SourcedMessages.js, src/react/components/_dashboard/TasksCard/CompletedTasks/CategoryTitle.module.scss, src/react/components/_dashboard/TasksCard/IncompleteTasks/Agreements.js, src/react/components/_dashboard/TasksCard/OverdueTasks/OverdueTask.module.scss
=> SISRP-48151: Minor notifications card fixes and comment cleanup

src/assets/templates/widgets/finaid_awards_term_widget.html
https://jira-secure.berkeley.edu/browse/SISRP-50496
DEV PR: #419
=> [QA] SISRP-50496 - Allows HTML in message on Awards by Term card

src/react/components/_dashboard/NotificationsCard/MessagesBySource.js, src/react/components/_dashboard/NotificationsCard/NoMessages.js, src/react/components/_dashboard/NotificationsCard/NotificationsCard.js, src/react/components/_dashboard/NotificationsCard/SourcedMessages.js, src/react/components/_dashboard/TasksCard/CompletedTasks/CategoryTitle.module.scss, src/react/components/_dashboard/TasksCard/IncompleteTasks/Agreements.js, src/react/components/_dashboard/TasksCard/OverdueTasks/OverdueTask.module.scss
=> [QA] SISRP-48151: Minor notifications card fixes and comment cleanup

app/models/user/b_courses/activity.rb, app/models/user/tasks/message_expiry.rb
https://jira-secure.berkeley.edu/browse/SISRP-48151
=> SISRP-48151: fix failures found during PRD deployment

src/react/components/_dashboard/UpNext/UpNextItem.js
https://jira-secure.berkeley.edu/browse/SISRP-46921
=> SISRP-46921 - Fixes date-fns v2.8.1 formatting

src/assets/javascripts/angular/controllers/widgets/finaid/finaidSummaryController.js, src/assets/templates/widgets/finaid_summary.html
https://jira-secure.berkeley.edu/browse/SISRP-50662
=> SISRP-50662: Fix endless spinner on FA & Scholarships

src/assets/javascripts/angular/controllers/widgets/finaid/finaidSummaryController.js
https://jira-secure.berkeley.edu/browse/SISRP-50662
=> SISRP-50662: re-assert loaded state is factory data is re-parsed

app/models/user/b_courses/activity.rb, app/models/user/tasks/message_expiry.rb, src/assets/javascripts/angular/controllers/widgets/finaid/finaidSummaryController.js, src/assets/templates/widgets/finaid_summary.html
https://jira-secure.berkeley.edu/browse/SISRP-50662
See DEV PR #424, #426, #427
=> [QA] SISRP-50662: production deployment bug-fixes

src/react/components/_finances/TransactionsCard/BillingItem/ItemUpdated.js
https://jira-secure.berkeley.edu/browse/SISRP-50739
=> SISRP-50739: Billing Summary transaction information isn't loading

src/react/components/_finances/TransactionsCard/BillingItem/ItemUpdated.js
https://jira-secure.berkeley.edu/browse/SISRP-50739
=> SISRP-50739: Unit argument changed

src/react/components/_finances/TransactionsCard/BillingItem/ItemUpdated.js
https://jira-secure.berkeley.edu/browse/SISRP-50739
See DEV PR #432, #433
=> [QA] SISRP-50739: Billing Summary transaction information isn't loading

jest.config.js, package.json, script/front-end-tests.sh, src/react/components/_finances/TransactionsCard/BillingItem/__tests__/ItemUpdated.test.js
https://jira-secure.berkeley.edu/browse/SISRP-50739
=> SISRP-50739: Add front-end tests for ItemUpdated

app/models/user/b_courses/activity.rb, spec/models/user/b_courses/activity_spec.rb
=> NOJIRA: address failed logger error with unknown bCourses types

public/dummy/json/up_next.json, src/react/components/_dashboard/UpNext/UpNextItem.js
https://jira-secure.berkeley.edu/browse/SISRP-46921
=> SISRP-46921 - Fixes Up Next item toggle behavior. Fixes attendees display logic

app/models/user/notifications/display.rb, spec/models/user/notifications/display_spec.rb, src/react/components/_dashboard/NotificationsCard/BCourses/SourceAndTypeGroup.module.scss, src/react/components/_dashboard/NotificationsCard/DateLabel.module.scss, src/react/components/_dashboard/NotificationsCard/Tabs.module.scss, src/react/components/_dashboard/NotificationsCard/University/Messages.module.scss, src/react/components/_dashboard/NotificationsCard/University/Unread.module.scss
https://jira-secure.berkeley.edu/browse/SISRP-48237
=> SISRP-48237: Address issues found in testing

src/assets/javascripts/angular/controllers/widgets/profile/workExperienceSectionController.js
https://jira-secure.berkeley.edu/browse/SISRP-50779
=> SISRP-50779 - Work Experience displays spinner when experience with date present

jest.config.js, src/react/components/_dashboard/TasksCard/CompletedTasks/CompletedTask.js, src/react/components/_dashboard/TasksCard/CompletedTasks/__tests__/CompletedTask.test.js, src/react/components/_dashboard/TasksCard/IncompleteTasks/ByCategory.js, src/react/components/_dashboard/TasksCard/IncompleteTasks/ForCategory.js, src/react/components/_dashboard/TasksCard/IncompleteTasks/__tests__/ByCategory.test.js
Also, completed tasks should show their "Waived" status
https://jira-secure.berkeley.edu/browse/SISRP-50820
=> SISRP-50820: Fix overdue sorting for in-process items

script/sis/verify_sis_api_endpoints.sh
https://jira-secure.berkeley.edu/browse/SISRP-50830
=> SISRP-50830 - Update verify_sis_api_endpoints.sh to use Student API v2 endpoints

app/controllers/application_controller.rb, app/models/user/authentication_validator.rb
=> [QA] SISRP-50465 - New Admit Blocked From Logging Into CLC W/O SIR

app/models/user/notifications/notification.rb, app/models/user/notifications/queries.rb, src/react/components/_dashboard/NotificationsCard/BCourses/DateGroup.js, src/react/components/_dashboard/NotificationsCard/BCourses/ForDate.js, src/react/components/_dashboard/NotificationsCard/BCourses/MultiNotifications.js, src/react/components/_dashboard/NotificationsCard/BCourses/SingleNotification.js, src/react/components/_dashboard/NotificationsCard/NotificationsCard.js, src/react/components/_dashboard/NotificationsCard/University/Messages.js, src/react/components/_dashboard/NotificationsCard/University/UniversityTab.js, src/react/components/_dashboard/NotificationsCard/University/Unread.module.scss, src/react/stylesheets/_colors.scss
https://jira-secure.berkeley.edu/browse/SISRP-48237
=> SISRP-48237: Notifications test fixes

src/react/components/_finances/FinancialResources/HasAccessTo.js, src/react/components/_finances/FinancialResources/WithAccess.js
https://jira-secure.berkeley.edu/browse/SISRP-50797
=> SISRP-50797 - allows Delegates access to Financial Resources without needing access to Academics

src/assets/javascripts/angular/services/dateService.js, src/assets/templates/widgets/sir/sir_item.html
https://jira-secure.berkeley.edu/browse/SISRP-50857
=> SISRP-50857: Admissions SIR card is missing Due Date

app/models/user/b_courses/activity.rb, app/models/user/webcasts/webcast.rb, src/react/components/_dashboard/NotificationsCard/BCourses/MultiNotifications.js, src/react/components/_dashboard/NotificationsCard/BCourses/SingleNotification.js, src/react/components/_dashboard/NotificationsCard/BCourses/notification.js
https://jira-secure.berkeley.edu/browse/SISRP-48237
=> SISRP-48237: Notification title and graded badges cleanup

src/assets/javascripts/angular/services/dateService.js, src/assets/templates/widgets/sir/sir_item.html, src/assets/templates/widgets/sir/sir_item_received.html
In date-fns v2 "Do" is now day of year, "do" is day of month with ordinal suffix (1st/3rd/5th)
https://jira-secure.berkeley.edu/browse/SISRP-50857
=> SISRP-50857: Update long date format

src/react/components/_finances/FinancialResources/HasAccessTo.js
https://jira-secure.berkeley.edu/browse/SISRP-50797
=> SISRP-50797 - prevent Delegate from seeing FAFSA link on Financial Resources

src/assets/javascripts/angular/controllers/widgets/enrollment/enrollmentCardController.js, src/assets/templates/widgets/enrollment_card.html
https://jira-secure.berkeley.edu/browse/SISRP-50889
=> SISRP-50889 - Spinner appears in Class Enrollment card after adding or dropping a class in QAT

src/assets/javascripts/angular/controllers/widgets/profile/workExperienceSectionController.js, src/assets/javascripts/angular/services/dateService.js, src/assets/templates/widgets/sir/sir_item.html, src/assets/templates/widgets/sir/sir_item_received.html
https://jira-secure.berkeley.edu/browse/SISRP-50857
See DEV PRs #453, #454, #456
=> [QA] SISRP-50857: Admissions SIR card is missing Due Date

src/assets/javascripts/angular/controllers/widgets/enrollment/enrollmentCardController.js, src/assets/templates/widgets/enrollment_card.html
https://jira-secure.berkeley.edu/browse/SISRP-50889
See DEV PR #459
=> [QA] SISRP-50889 - Spinner appears in Class Enrollment card after adding or dropping a class

app/models/berkeley/user_roles.rb, app/models/edo_oracle/queries.rb, app/models/user/aggregated_attributes.rb, src/assets/javascripts/angular/controllers/pages/academicsController.js, src/assets/templates/academics.html, src/assets/templates/dashboard.html
=> [QA] SISRP-48144 - Withdrawn Admits - Experience in CalCentral

src/assets/javascripts/angular/controllers/widgets/enrollment/enrollmentCardController.js
https://jira-secure.berkeley.edu/browse/SISRP-50889
See DEV PR #467
=> [QA] SISRP-50889 - Spinner appears in Class Enrollment card after adding or dropping a class in QAT

src/assets/javascripts/angular/services/profileMenuService.js, src/assets/templates/launcher.html, src/assets/templates/no_bconnected.html, src/assets/templates/widgets/badges_popover.html, src/assets/templates/widgets/hookup_google_reminder.html, src/assets/templates/widgets/profile/bconnected_service_loop.html, src/assets/templates/widgets/tasks.html, src/react/components/_dashboard/UpNext/UpNextCard.js, src/react/components/_dashboard/bConnected/NoBconnected.js
This reverts front-end work from commit b87b250.
https://jira-secure.berkeley.edu/browse/SISRP-48140
See DEV Revert PR #463
This is getting pushed to a release after 03/08 due to issues testing in CLC-QA
=> SISRP-48140 - Reverts front-end changes from b87b250 (omits reverting back-end changes to SessionsController and UserController

src/assets/javascripts/angular/services/profileMenuService.js, src/assets/templates/launcher.html, src/assets/templates/no_bconnected.html, src/assets/templates/widgets/badges_popover.html, src/assets/templates/widgets/hookup_google_reminder.html, src/assets/templates/widgets/profile/bconnected_service_loop.html, src/assets/templates/widgets/tasks.html, src/react/components/_dashboard/UpNext/UpNextCard.js, src/react/components/_dashboard/bConnected/NoBconnected.js
This reverts front-end work from commit b87b25042fa8ecf21a908f1187028194437633d8.
https://jira-secure.berkeley.edu/browse/SISRP-48140
See DEV Revert PR #469
This is getting pushed to a release after 03/08 due to issues testing in CLC-QA
=> [QA] Reverts front-end changes from b87b250 (omits reverting back-end changes to SessionsController and UserController

app/models/user/tasks/checklist_item.rb, app/models/user/tasks/completed_checklist_item.rb, app/models/user/tasks/incomplete_checklist_item.rb, app/models/user/tasks/incomplete_checklist_items.rb, app/models/user/tasks/queries.rb, spec/models/user/tasks/checklist_item_spec.rb, spec/models/user/tasks/incomplete_checklist_items_spec.rb, src/react/components/_dashboard/TasksCard/IncompleteTasks/ByCategory.js, src/react/components/_dashboard/TasksCard/IncompleteTasks/__tests__/ByCategory.test.js
https://jira-secure.berkeley.edu/browse/SISRP-50820
=> SISRP-50820: Admissions Tasks with Received status display as OverDue

src/assets/templates/widgets/finaid/housing.html, src/assets/templates/widgets/finaid_communications.html
https://jira-secure.berkeley.edu/browse/SISRP-50797
=> SISRP-50797 - prevent Delegate from seeing additional Financial Aid links

script/sis/verify_sis_api_endpoints.sh
https://jira-secure.berkeley.edu/browse/SISRP-50830
See DEV PR #447 and #473
=> [QA] SISRP-50830 - Update verify_sis_api_endpoints.sh to use Student API v2 endpoints

script/sis/verify_sis_api_endpoints.sh
https://jira-secure.berkeley.edu/browse/SISRP-50830
=> SISRP-50830 - Remove detection of 'error' in API payload to indicate error, to avoid false positives

src/assets/templates/widgets/finaid/housing.html, src/assets/templates/widgets/finaid_communications.html
https://jira-secure.berkeley.edu/browse/SISRP-50797
DEV PR: https://github.com/sis-berkeley-edu/calcentral/pull/471
=> [QA] SISRP-50797 - prevent Delegate from seeing additional Financial Aid Links

src/react/components/_dashboard/TasksCard/IncompleteTasks/ForCategory.js
https://jira-secure.berkeley.edu/browse/SISRP-50820
=> SISRP-50820: Fix subcategory groupings

src/assets/javascripts/angular/services/dateService.js
https://jira-secure.berkeley.edu/browse/SISRP-50744
=> SISRP-50744 - Updates dateService.format to support date, string, or epoch number

src/assets/javascripts/angular/services/dateService.js
https://jira-secure.berkeley.edu/browse/SISRP-50744
See DEV PR #476
=> [QA] SISRP-50744 - Updates dateService.format to support date, string, or epoch number

app/models/user/tasks/agreement.rb, app/models/user/tasks/checklist_item.rb, app/models/user/tasks/completed_agreement.rb, app/models/user/tasks/completed_checklist_item.rb, app/models/user/tasks/display_category.rb, app/models/user/tasks/incomplete_agreement.rb, app/models/user/tasks/incomplete_checklist_item.rb, spec/models/user/tasks/agreement_spec.rb, spec/models/user/tasks/checklist_item_spec.rb, src/react/components/_finances/FinancialAidTasks.js
=> SISRP-50734: Tasks Card - Updates for BDGT (CLC DEV)

src/assets/javascripts/angular/services/profileMenuService.js, src/assets/templates/widgets/badges_popover.html, src/react/components/_dashboard/bConnected/NoBconnected.js
https://jira-secure.berkeley.edu/browse/SISRP-50955
See DEV JIRA #480
=> [QA] SISRP-50955 - Minor bConnected experience touchups

app/models/user/academics/degree_progress/graduate/requirement.rb
https://jira-secure.berkeley.edu/browse/SISRP-51068
=> SISRP-51068 - CalCentral degree progress load bug - INC1016847

app/models/user/tasks/checklist_item.rb, app/models/user/tasks/completed_checklist_item.rb, app/models/user/tasks/incomplete_checklist_item.rb, app/models/user/tasks/incomplete_checklist_items.rb, app/models/user/tasks/queries.rb, jest.config.js, spec/models/user/tasks/checklist_item_spec.rb, spec/models/user/tasks/incomplete_checklist_items_spec.rb, src/react/components/_dashboard/TasksCard/CompletedTasks/CompletedTask.js, src/react/components/_dashboard/TasksCard/CompletedTasks/__tests__/CompletedTask.test.js, src/react/components/_dashboard/TasksCard/IncompleteTasks/ByCategory.js, src/react/components/_dashboard/TasksCard/IncompleteTasks/ForCategory.js, src/react/components/_dashboard/TasksCard/IncompleteTasks/__tests__/ByCategory.test.js
https://jira-secure.berkeley.edu/browse/SISRP-50820
See DEV #445, #470, #475
=> [QA] SISRP-50820: Admissions Tasks with Received status display as OverDue

app/models/campus_solutions/student_resources.rb, spec/models/campus_solutions/student_resources_spec.rb
https://jira-secure.berkeley.edu/browse/SISRP-51095
=> SISRP-51095 - Remove Expected Grad Term and Final Signature form links from JD and LLM Law Student CalCentral (EGT)

app/models/user/academics/degree_progress/graduate/requirement.rb
=> [QA] SISRP-51068 - CalCentral degree progress load bug - INC1016847

app/models/campus_solutions/student_resources.rb, spec/models/campus_solutions/student_resources_spec.rb
=> [QA] SISRP-51095 - Remove Expected Grad Term and Final Signature form links from JD and LLM Law Student CalCentral (EGT) 

src/react/components/_academics/EnrollmentLinks/EnrollmentLinks.js
https://jira-secure.berkeley.edu/browse/SISRP-51155
=> SISRP-51155: Update enrollment card CA Enrollment Acknowledgement text

app/models/enf/message.rb, app/models/enf/processor.rb, app/models/notifications/sis_expiry_processor.rb, app/models/user/notifications/expiry.rb, app/models/user/tasks/expiry.rb, lib/services/jms_worker.rb, spec/models/enf/jms_message_factory.rb, spec/models/enf/message_spec.rb, spec/models/enf/processor_spec.rb
https://jira-secure.berkeley.edu/browse/SISRP-51107
=> SISRP-51107: Update agreements ENF

src/react/components/_finances/AidYearTaskCount.js
=> SISRP-50734: Limit AidYearTaskCount component to finaid tasks

src/react/components/_academics/EnrollmentLinks/EnrollmentLinks.js
https://jira-secure.berkeley.edu/browse/SISRP-51155
=> SISRP-51155 - Update enrollment card CA Enrollment Acknowledgement text pt 2

src/assets/javascripts/angular/controllers/widgets/sir/sirItemController.js, src/assets/stylesheets/_buttons.scss, src/assets/templates/widgets/sir/sir_item.html
https://jira-secure.berkeley.edu/browse/SISRP-46661
=> SISRP-46661 sir accept button

app/models/enf/message.rb, app/models/user/current.rb, spec/models/enf/message_spec.rb
https://jira-secure.berkeley.edu/browse/SISRP-51107
=> SISRP-51107: Fix ENF UID lookup

app/models/user/tasks/incomplete_checklist_item.rb, app/models/user/tasks/queries.rb
https://jira-secure.berkeley.edu/browse/SISRP-51267
=> SISRP-51267: Add SPRG Admin Function Checklist Upload

src/react/components/_finances/FinancialAidTasks.js
=> SISRP-50734: Fix task status for in-process items on finaid awards page

app/models/enf/message.rb, app/models/enf/processor.rb, app/models/notifications/sis_expiry_processor.rb, app/models/user/current.rb, app/models/user/notifications/expiry.rb, app/models/user/tasks/expiry.rb, lib/services/jms_worker.rb, spec/models/enf/jms_message_factory.rb, spec/models/enf/message_spec.rb, spec/models/enf/processor_spec.rb
https://jira-secure.berkeley.edu/browse/SISRP-51107
=> [QA] SISRP-51107: Update agreements ENF

src/react/components/_academics/EnrollmentLinks/EnrollmentLinks.js
https://jira-secure.berkeley.edu/browse/SISRP-51155
See Dev PR: #494, #497
=> [QA] SISRP-51155: Update enrollment card CA Enrollment Acknowledgement text

app/models/user/tasks/agreement.rb, app/models/user/tasks/checklist_item.rb, app/models/user/tasks/completed_agreement.rb, app/models/user/tasks/completed_checklist_item.rb, app/models/user/tasks/display_category.rb, app/models/user/tasks/incomplete_agreement.rb, app/models/user/tasks/incomplete_checklist_item.rb, spec/models/user/tasks/agreement_spec.rb, spec/models/user/tasks/checklist_item_spec.rb, src/react/components/_finances/AidYearTaskCount.js, src/react/components/_finances/FinancialAidTasks.js
=> [QA] SISRP-50734: Tasks Card - Updates for BDGT

app/models/user/tasks/incomplete_checklist_item.rb, app/models/user/tasks/queries.rb
https://jira-secure.berkeley.edu/browse/SISRP-51267
See DEV PR #496
=> [QA] SISRP-51267: Add SPRG Admin Function Checklist Upload

src/react/components/_dashboard/NotificationsCard/notifications.module.js, src/react/components/_finances/FinancialAidMessages.js
=> SISRP-50734: Fix late-breaking financial aid messages bug

src/react/components/_dashboard/NotificationsCard/notifications.module.js, src/react/components/_finances/FinancialAidMessages.js
=> [QA] SISRP-50734: Fix late-breaking financial aid messages bug

app/models/degree_progress/my_undergrad_requirements.rb, config/settings.yml
https://jira-secure.berkeley.edu/browse/SISRP-47619
=> SISRP-47619 - Update UGRD Degree Progress Card to show APR link for UCCH students

app/models/enf/handler.rb, app/models/user/cards/enrollment_expiry.rb, app/models/user/tasks/expiry.rb
https://jira-secure.berkeley.edu/browse/SISRP-51328
=> SISRP-51328: Expire enrollment card on sis:student:messages

app/controllers/cache_controller.rb, config/routes.rb
https://jira-secure.berkeley.edu/browse/SISRP-51329
=> SISRP-51329: Allow clearing user specific cache-keys

src/react/components/_academics/AcademicSummary/Semester.js
https://jira-secure.berkeley.edu/browse/SISRP-51280
=> SISRP-51280 - COVID-19 note for law students in CalCentral

app/models/user/b_courses/event.rb, app/models/user/b_courses/events.rb
https://jira-secure.berkeley.edu/browse/SISRP-51378
=> SISRP-51378: Display bCourses tasks from events with assignments

app/models/enf/handler.rb, app/models/user/cards/enrollment_expiry.rb, app/models/user/tasks/expiry.rb
https://jira-secure.berkeley.edu/browse/SISRP-51328
See DEV PR #509
=> [QA] SISRP-51328: Expire enrollment card on sis:student:messages

src/react/components/_academics/AcademicSummary/Semester.js
=> [QA] SISRP-51280 - COVID-19 note for law students in CalCentral

app/models/user/b_courses/event.rb, app/models/user/b_courses/events.rb
https://jira-secure.berkeley.edu/browse/SISRP-51378
See DEV PR #512
=> [QA] SISRP-51378: Display bCourses tasks from events with assignments

app/models/campus_solutions/student_resources.rb, spec/models/campus_solutions/student_resources_spec.rb
SISRP-49889: GRADCPP - Law JSP students- add link to eform - Calcentral
=> SISRP-49889: GRADCPP - Law JSP students- add link to eform - Calcentral

src/assets/templates/widgets/transfer_credit.html, src/react/components/_academics/TransferCredit/LawTransferCredit.js
https://jira-secure.berkeley.edu/browse/SISRP-49845
Law student transfer credits are not adding up correctly
=> SISRP-49845: Law student transfer credits are not adding up correctly

src/react/components/ButtonGroup.scss, src/react/components/_finances/TransactionsCard/DownloadButton.scss
https://jira-secure.berkeley.edu/browse/SISRP-49220
React button maintenance - Part 2
=> SISRP-49220-react-button-color

app/models/hub_edos/student_api/v2/registrations.rb, app/models/user/academics/null_term.rb, app/models/user/academics/term.rb, app/models/user/academics/term_registrations.rb
https://jira-secure.berkeley.edu/browse/SISRP-51430
=> SISRP-51430: Show upcoming terms in Status and Holds card

src/react/components/ButtonGroup.scss, src/react/components/_finances/TransactionsCard/DownloadButton.scss
React button maintenance - Part 2
https://jira-secure.berkeley.edu/browse/SISRP-49220
PR to master: 
https://github.com/sis-berkeley-edu/calcentral/pull/523
=> QA-SISRP-49220-react-button-color

app/models/campus_solutions/student_resources.rb, spec/models/campus_solutions/student_resources_spec.rb
GRADCPP - Law JSP students- add link to eform - Calcentral
https://jira-secure.berkeley.edu/browse/SISRP-49889
Dev PR to Master:
https://github.com/sis-berkeley-edu/calcentral/pull/518
=> QA-SISRP-49889 law students link eform

src/react/components/_academics/PnpCalculator/CurrentGradePercentage.js
https://jira-secure.berkeley.edu/browse/SISRP-51535
=> SISRP-51535 - Update P/NP Calculator for COVID 19 P/NP Policy Change

app/models/hub_edos/student_api/v2/registrations.rb, app/models/user/academics/null_term.rb, app/models/user/academics/term.rb, app/models/user/academics/term_registrations.rb
https://jira-secure.berkeley.edu/browse/SISRP-51430
See DEV PR #525
=> [QA] SISRP-51430: Show upcoming terms in Status and Holds card

src/react/components/_academics/COVIDEnrollmentNotice.js
https://jira-secure.berkeley.edu/browse/SISRP-51476
=> SISRP-51476: Don't show P/NP notice if message is empty

app/models/user/academics/term_registration.rb, spec/models/user/academics/term_registration_spec.rb
https://jira-secure.berkeley.edu/browse/SISRP-51237
=> SISRP-51237 - Enrollment Card not Showing for Student

app/models/user/academics/term_registration.rb, spec/models/user/academics/term_registration_spec.rb
https://jira-secure.berkeley.edu/browse/SISRP-51237
See DEV PR #535
=> [QA] SISRP-51237 - Enrollment Card not Showing for Student

app/models/campus_solutions/student_resources.rb, app/models/my_academics/class_enrollments.rb, spec/controllers/my_class_enrollments_controller_spec.rb, src/assets/templates/widgets/enrollment/adjust_enrolled.html, src/react/components/CampusSolutionsLink/CampusSolutionsLink.js, src/react/components/CampusSolutionsLink/CampusSolutionsLinkContainer.js, src/react/components/CampusSolutionsLink/CampusSolutionsOutboundLink.js, src/react/components/_dashboard/StudentResources/StudentResources.js, src/react/components/_dashboard/StudentResources/StudentResourcesContainer.js
https://jira-secure.berkeley.edu/browse/SISRP-51452
=> SISRP-51452 - Add Link to eForm May 6 Drop Deadline

src/react/components/_academics/PnpCalculator/CurrentGradePercentage.js
https://jira-secure.berkeley.edu/browse/SISRP-51535
QA PR for #539
=> [QA] SISRP-51535 - Update P/NP Calculator for COVID 19 P/NP Policy Change

app/models/campus_solutions/student_resources.rb, app/models/my_academics/class_enrollments.rb, spec/controllers/my_class_enrollments_controller_spec.rb, src/assets/templates/widgets/enrollment/adjust_enrolled.html, src/react/components/CampusSolutionsLink/CampusSolutionsLink.js, src/react/components/CampusSolutionsLink/CampusSolutionsLinkContainer.js, src/react/components/CampusSolutionsLink/CampusSolutionsOutboundLink.js, src/react/components/_dashboard/StudentResources/StudentResources.js, src/react/components/_dashboard/StudentResources/StudentResourcesContainer.js
https://jira-secure.berkeley.edu/browse/SISRP-51452
QA PR for #538
=> [QA] SISRP-51452 - Add Link to eForm May 6 Drop Deadline

src/assets/stylesheets/_profile.scss, src/assets/templates/widgets/toolbox/user_preview.html
https://jira-secure.berkeley.edu/browse/SISRP-50112
Create link from Student Overview page in CalCentral to BOA (CLC dev)
=> SISRP-50112: Create link from Student Overview page in CalCentral to BOA

app/models/my_academics/gpa_units.rb, app/models/my_academics/semesters.rb, src/react/components/_academics/AcademicSummary/LawSection.js, src/react/components/_academics/AcademicSummary/PrimarySection.js, src/react/components/_academics/AcademicSummary/SemesterSections.js, src/react/components/_academics/AcademicSummary/SemestersSummary.js, src/react/components/_academics/StudentProfile/CumulativeUnits.js, src/react/components/_academics/StudentProfile/GPA.js
https://jira-secure.berkeley.edu/browse/SISRP-49844
CalCentral Old and New Envir: Summary Totals on Law Academic Summary Incorrect
=> SISRP-49844: CalCentral Old and New Envir: Summary Totals on Law Academic

app/controllers/google_auth_controller.rb, app/models/google_apps/client.rb, app/models/google_apps/credential_store.rb, app/models/google_apps/oauth2_tokens_grant.rb, app/models/google_apps/proxy.rb, app/models/google_apps/userinfo.rb, app/models/user/oauth2_data.rb, db/migrate/20131206145401_remove_canvas_oauth_data.rb, db/migrate/20190422180339_create_ps_uc_saved_uids.rb, db/migrate/20190502203150_remove_ets_tables.rb, db/migrate/20190502204723_remove_campus_link_tables.rb, db/migrate/20200417192341_remove_app_id_from_oauth2_data.rb, db/schema.rb, spec/controllers/google_auth_controller_spec.rb, spec/models/canvas/user_activity_stream_spec.rb, spec/models/google_apps/credential_store_spec.rb, spec/models/user/oauth2_data_spec.rb
https://jira-secure.berkeley.edu/browse/SISRP-49809
=> SISRP-49809 - Removes app_id support from Google OAuth table

app/models/campus_solutions/student_resources.rb, app/models/concerns/academic_roles.rb, spec/models/concerns/academic_roles_spec.rb, spec/models/my_academics/my_academic_roles_spec.rb
https://jira-secure.berkeley.edu/browse/SISRP-49807
=> SISRP-49807 - Veteran Benefit Semester Renewal eForm

src/react/components/_finances/AwardComparison/AwardComparison.scss
=> SISRP-49141 - Award Comparison card styling adjustments

app/models/edo_oracle/financial_aid/queries.rb, src/assets/templates/widgets/finaid_awards.html, src/react/components/Badge.js, src/react/components/_finances/AwardComparison/AwardComparison.scss, src/react/components/_finances/AwardComparison/AwardComparisonLink.js, src/react/components/_finances/AwardComparison/Awards.js, src/react/components/_finances/AwardComparison/Dropdowns.scss, src/react/components/_finances/AwardComparison/Legend.js, src/react/components/_finances/AwardComparison/SectionHeader.js, src/react/stylesheets/_colors.scss
=> SISRP-49141 - Award Comparison UX updates

app/models/campus_solutions/student_resources.rb, app/models/concerns/academic_roles.rb, spec/models/concerns/academic_roles_spec.rb, spec/models/my_academics/my_academic_roles_spec.rb
=> [QA] SISRP-49807 - Veteran Benefit Semester Renewal eForm

app/models/concerns/academic_roles.rb, app/models/my_academics/law/queries.rb, app/models/my_academics/my_academic_roles.rb, spec/models/concerns/academic_roles_spec.rb, spec/models/my_academics/my_academic_roles_spec.rb, src/assets/templates/academics.html, src/react/components/CampusSolutionsLink/CampusSolutionsLink.js, src/react/components/CampusSolutionsLink/CampusSolutionsOutboundLink.js, src/react/components/_academics/LawDegreeAudit/LawDegreeAudit.js, src/react/components/index.js
https://jira-secure.berkeley.edu/browse/SISRP-45233
=> SISRP-45233 - Create a Law Degree Progress Card

app/models/user/academics/degree_progress/graduate/student_links.rb, spec/models/degree_progress/my_graduate_milestones_spec.rb, spec/models/user/academics/degree_progress/graduate/student_links_spec.rb, src/assets/templates/widgets/academics/degree_progress_graduate.html
https://jira-secure.berkeley.edu/browse/SISRP-50492
=> SISRP-50492 - Update APR link on CLC Grad Degree Progress Card

app/models/user/academics/academics_concern.rb, app/models/user/academics/enrollment_career.rb, app/models/user/academics/enrollment_careers.rb, app/models/user/academics/enrollment_period.rb, app/models/user/academics/enrollment_periods.rb, app/models/user/academics/enrollment_term.rb, app/models/user/academics/enrollment_term_instruction.rb, app/models/user/academics/enrollment_term_instructions.rb, app/models/user/academics/enrollment_terms.rb, src/assets/templates/widgets/enrollment/decide.html, src/react/components/_academics/EnrollmentAppointments/Deadlines.js, src/react/components/_academics/EnrollmentAppointments/EnrollmentAppointments.js, src/react/components/_academics/EnrollmentAppointments/LawEnrollmentAppointments.js, src/react/components/_academics/EnrollmentAppointments/TimeCell.js, src/react/components/index.js
https://jira-secure.berkeley.edu/browse/SISRP-48765
=> SISRP-48765: Improve Appointment information

app/models/my_academics/college_and_level.rb
https://jira-secure.berkeley.edu/browse/SISRP-49957
=> SISRP-49957 - Issues with Minors not appearing in CLC degree area

app/models/user/academics/academics_concern.rb, app/models/user/academics/enrollment_term.rb, app/models/user/academics/enrollment_terms.rb, app/models/user/academics/term_plans/term_plans.rb, src/react/components/_academics/EnrollmentAppointments/Deadlines.js, src/react/components/_academics/EnrollmentAppointments/EnrollmentAppointments.js
https://jira-secure.berkeley.edu/browse/SISRP-48765
=> SISRP-48765: Add Engineering/Chem policy note

app/models/my_academics/gpa_units.rb
CalCentral Old and New Envir: Summary Totals on Law Academic Summary Incorrect
https://jira-secure.berkeley.edu/browse/SISRP-49844
- add IF condition to add previous acad_career
=> SISRP-49844-law-academic-summary-incorrect

app/models/user/financial_aid/queries.rb, src/react/components/_finances/AwardComparison/SubvaluesComparisonRow.js
=> SISRP-49141 - Award Comparison fixes

src/react/components/_finances/AwardComparison/AwardComparisonLink.js
=> SISRP-49141 Award Comparison Fixes

config/deploy.rb, script/calcentral-update.sh, script/update-build-tomcat-test.sh, script/update-build.sh
This reverts commit 838153afa2f6e70b229694e9d7693eac6a2f309e.
=> Revert "NOJIRA: Complete the transition to hot deployments"

src/assets/templates/academics.html
https://jira-secure.berkeley.edu/browse/SISRP-45233
=> SISRP-45233 - Law Degree Audit fix

src/assets/templates/academics.html
https://jira-secure.berkeley.edu/browse/SISRP-45233
=> [QA]SISRP-45233 - Law Degree Audit fix

app/models/user/tasks/checklist_item.rb, app/models/user/tasks/incomplete_checklist_item.rb
https://jira-secure.berkeley.edu/browse/SISRP-52145
=> SISRP-52145: Update tasks card to handle "Notified" status

src/react/components/Card.js, src/react/components/_finances/AwardComparison/Awards.js, src/react/components/_finances/AwardComparison/CostOfAttendance.js, src/react/components/_finances/AwardComparison/Instructions.js, src/react/components/_finances/AwardComparison/Legend.js, src/react/components/_finances/AwardComparison/Profile.js, src/react/components/_finances/AwardComparison/Summary.js
=> SISRP-49141 - Award Comparison - facilitates keyboard navigation

src/react/components/Card.js, src/react/components/_finances/AwardComparison/Awards.js, src/react/components/_finances/AwardComparison/CostOfAttendance.js, src/react/components/_finances/AwardComparison/Instructions.js, src/react/components/_finances/AwardComparison/Legend.js, src/react/components/_finances/AwardComparison/Profile.js, src/react/components/_finances/AwardComparison/Summary.js
=> [QA] SISRP-49141 - Award Comparison - facilitates keyboard navigation

app/models/eft/my_eft_enrollment.rb, app/models/notifications/sis_expiry_processor.rb
https://jira-secure.berkeley.edu/browse/SISRP-50462
=> SISRP-50462: Remove sis:student:eft cache clearing code

src/react/components/_academics/AcademicSummary/PrimarySection.js, src/react/components/_academics/StudentProfile/Degrees.js, src/react/components/_academics/StudentProfile/StudentProfileCard.js, src/react/components/_academics/TransferCredit/TransferCredit.js
https://jira-secure.berkeley.edu/browse/SISRP-52001
=> SISRP-52001: Show Degree Honors on Profile and Summary

app/models/edo_oracle/queries.rb
https://jira-secure.berkeley.edu/browse/SISRP-52294
=> SISRP-52294 - Summer sections processing error causing My Classes card spinner

src/assets/templates/widgets/exam_results_card.html
https://jira-secure.berkeley.edu/browse/SISRP-51999
Exam Results Card Displaying Wrong Dates (CLC DEV)
=> SISRP-51999: Exam Results Card Displaying Wrong Dates

app/models/edo_oracle/queries.rb
https://jira-secure.berkeley.edu/browse/SISRP-52294
See DEV PR #586
=> [QA] SISRP-52294 - Summer sections processing error causing My Classes card spinner

src/assets/templates/widgets/exam_results_card.html
Exam Results Card Displaying Wrong Dates (CLC DEV)
https://jira-secure.berkeley.edu/browse/SISRP-51999
See Dev PR #589
=> [QA] SISRP-51999: Exam Results Card Displaying Wrong Dates

src/react/components/_academics/AcademicSummary/PrimarySection.js, src/react/components/_academics/StudentProfile/Degrees.js, src/react/components/_academics/StudentProfile/StudentProfileCard.js, src/react/components/_academics/TransferCredit/TransferCredit.js
https://jira-secure.berkeley.edu/browse/SISRP-52001
See DEV PR #587
=> [QA] SISRP-52001: Show Degree Honors on Profile and Summary

app/models/user/tasks/checklist_item.rb, app/models/user/tasks/incomplete_checklist_item.rb
https://jira-secure.berkeley.edu/browse/SISRP-52145
See DEV PR #584
=> [QA] SISRP-52145: Update tasks card to handle "Notified" status

app/models/user/financial_aid/cached_award_comparison_data.rb, src/react/components/_finances/AwardComparison/AwardComparison.scss
https://jira-secure.berkeley.edu/browse/SISRP-49958
=> SISRP-49958 - Award Comparison fixes for missing ISIR data

app/models/my_academics/college_and_level.rb, src/assets/templates/widgets/exam_results_card.html
Exam Results Card - Remove text (CLC DEV)
https://jira-secure.berkeley.edu/browse/SISRP-52377
=> SISRP-52377: Exam Results Card - Remove text

app/controllers/concerns/advising_resources.rb, app/models/campus_solutions/faculty_resources.rb, app/models/campus_solutions/student_resources.rb, app/models/links/my_campus_links.rb, package-lock.json, public/json/campuslinks.json, spec/controllers/concerns/advising_resources_spec.rb, spec/controllers/photo_controller_spec.rb, spec/models/campus_solutions/student_resources_spec.rb, spec/models/links/my_campus_links_spec.rb, src/assets/javascripts/angular/controllers/widgets/advising/advisingResourcesController.js, src/assets/javascripts/angular/factories/campusLinksFactory.js, src/assets/stylesheets/_lists.scss, src/assets/templates/campus_link_list.html, src/assets/templates/faculty_resources.html
=> SISRP-51472 - Request to add link to Academic Accommodations Hub on CalCentral

public/json/campuslinks.json
=> SISRP-51472 - Removes conflicting Counseling & Psychology Services link configuration

public/json/campuslinks.json
=> SISRP-51472 - Adds Counseling & Psychological Services back to Support Services section

app/models/edo_oracle/financial_aid/queries.rb
https://jira-secure.berkeley.edu/browse/SISRP-47960
=> SISRP-47960 - Adds Tuition and Fee Remissions disbursement date to Awards Card

app/controllers/concerns/advising_resources.rb, app/models/campus_solutions/faculty_resources.rb, app/models/campus_solutions/student_resources.rb, app/models/links/my_campus_links.rb, package-lock.json, public/json/campuslinks.json, spec/controllers/concerns/advising_resources_spec.rb, spec/controllers/photo_controller_spec.rb, spec/models/campus_solutions/student_resources_spec.rb, spec/models/links/my_campus_links_spec.rb, src/assets/javascripts/angular/controllers/widgets/advising/advisingResourcesController.js, src/assets/javascripts/angular/factories/campusLinksFactory.js, src/assets/stylesheets/_lists.scss, src/assets/templates/campus_link_list.html, src/assets/templates/faculty_resources.html
=> [QA] SISRP-51472 - Adds Counseling & Psychological Services back to Support Services section

app/models/my_academics/college_and_level.rb, src/assets/templates/widgets/exam_results_card.html
https://jira-secure.berkeley.edu/browse/SISRP-52377
Exam Results Card - Remove text (CLC DEV)
see https://github.com/sis-berkeley-edu/calcentral/pull/596
=> [QA] SISRP-52377 - Exam Results Card - Remove text

config/deploy.rb, script/run_deploy_main.sh, script/update-build-tomcat.sh
https://jira-secure.berkeley.edu/browse/SISRP-52450
=> SISRP-52450: Add hot deploy scripts

public/json/campuslinks.json
=> SISRP-51472 - Adds Gender Equity Resource Center and OHPD link under Staff and Faculty Resources section

app/controllers/google_auth_controller.rb, app/models/google_apps/auth/token_store.rb, src/assets/stylesheets/_header.scss
https://jira-secure.berkeley.edu/browse/SISRP-51849
=> SISRP-51849 - UX Maintenance: Upgrade Google API Client Gem - Cleanup

src/assets/stylesheets/_finaid_awards.scss, src/react/components/_academics/DegreeProgress/DegreeProgressLinks.js, src/react/components/_academics/DegreeProgress/DegreeProgressLinks.scss
https://jira-secure.berkeley.edu/browse/SISRP-48695
=> SISRP-48695 - Degree Progress Links fixes

public/json/campuslinks.json
=> [QA] SISRP-51472 - Adds Gender Equity Resource Center and OHPD link under Staff and Faculty Resources section

src/react/components/_academics/StudentProfile/CumulativeUnits.js
https://jira-secure.berkeley.edu/browse/SISRP-52297
Updated component with Prettier formatting. The functional change is on line 60: `summaryTotalTransferUnits.toFixed(3)`
=> SISRP-52297: Fix floating point display of Transfer Units

public/json/campuslinks.json
https://jira-secure.berkeley.edu/browse/SISRP-52532
=> SISRP-52532 - Update links with 301 redirects for 'My Campus' page

app/models/edo_oracle/user_courses/base.rb, app/models/edo_oracle/user_courses/section.rb, app/models/my_academics/semesters.rb, spec/models/my_academics/semesters_spec.rb, src/react/components/_academics/AcademicSummary/LawSection.js, src/react/components/_academics/AcademicSummary/PrimarySection.js
https://jira-secure.berkeley.edu/browse/SISRP-52439
It was previously assumed that the could only be one requirements
designation per class, instead of per section.
=> SISRP-52439: Source Requirement Designation per section

src/assets/templates/widgets/academic_plan.html
https://jira-secure.berkeley.edu/browse/SISRP-48695
=> SISRP-48695 - Degree Planner Links - fixes link for advisors

config/deploy.rb, script/run_deploy_main.sh, script/update-build-tomcat.sh
=> [QA] SISRP-52450: Add hot deploy scripts

src/react/components/_academics/AcademicSummary/SemestersSummary.js, src/react/components/_academics/StudentProfile/CumulativeUnits.js
https://jira-secure.berkeley.edu/browse/SISRP-52256
2005 Previous Graduate Data showing in CalCentral for an active Law Student
=> SISRP-52256: Previous Graduate Data showing for an active Law Student

app/models/campus_solutions/message_catalog.rb, app/models/user/academics/enrollment_term.rb, app/models/user/academics/null_term.rb, app/models/user/academics/term.rb, src/react/components/_academics/COVIDEnrollmentNotice.js
https://jira-secure.berkeley.edu/browse/SISRP-52453
=> SISRP-52453: Add message catalog enrollment notice for future terms

src/assets/templates/academics_graduation_checklist.html
https://jira-secure.berkeley.edu/browse/SISRP-52624
=> SISRP-52624 - Grad Checklist CLC text update

src/react/components/_academics/COVIDEnrollmentNotice.js
https://jira-secure.berkeley.edu/browse/SISRP-52453
Addresses accessibility issue found and addressed in the QA PR by @marcpechaitis (🙏)
See DEV PR #622 and QA PR #625
=> SISRP-52453: Add aria-expanded to expandable message

app/models/campus_solutions/message_catalog.rb, app/models/user/academics/enrollment_term.rb, app/models/user/academics/null_term.rb, app/models/user/academics/term.rb, src/react/components/_academics/COVIDEnrollmentNotice.js
https://jira-secure.berkeley.edu/browse/SISRP-52453
See DEV PR #622
=> [QA] SISRP-52453: Add message catalog enrollment notice for future terms

src/assets/javascripts/angular/controllers/widgets/academics/graduateDegreeProgressController.js
https://jira-secure.berkeley.edu/browse/SISRP-52256
2005 Previous Graduate Data showing in CalCentral for an active Law Student
=> SISRP-52556 Previous Graduate Data showing for an active Law Student

package-lock.json, package.json, src/react/components/_academics/EnrollmentAppointments/TimeCell.js
https://jira-secure.berkeley.edu/browse/SISRP-52659
=> SISRP-52659: Update TimeCell to always use America/Los_Angeles zone

src/assets/templates/widgets/academics/degree_progress_undergrad.html
https://jira-secure.berkeley.edu/browse/SISRP-48817
=> SISRP-48817 - Remove student notice from Advisor Degree Requirements card

package-lock.json, package.json, src/react/components/_academics/EnrollmentAppointments/TimeCell.js
https://jira-secure.berkeley.edu/browse/SISRP-52659
See DEV PR #631
=> [QA] SISRP-52659: Update TimeCell to always use America/Los_Angeles zone

public/json/campuslinks.json
https://jira-secure.berkeley.edu/browse/SISRP-52532
=> SISRP-52532 - Update 301 redirects in My Campus pages

app/models/user/financial_aid/cached_award_comparison_data.rb
https://jira-secure.berkeley.edu/browse/SISRP-52666
=> SISRP-52666 - fixes EFC on Award Comparison card

app/models/campus_solutions/link.rb, spec/models/campus_solutions/link_spec.rb, src/assets/javascripts/angular/controllers/widgets/academics/undergraduateDegreeProgressController.js, src/assets/javascripts/angular/services/analyticsService.js, src/assets/templates/academics_class_sites.html, src/assets/templates/campus_link_list.html, src/assets/templates/dashboard_task_loop.html, src/assets/templates/widgets/activity_list_link.html, src/assets/templates/widgets/my_classes.html, src/assets/templates/widgets/my_groups.html, src/assets/templates/widgets/toolbox/user_preview.html, src/functions/googleAnalytics.js, src/react/components/APILink.js, src/react/components/_academics/DegreeProgress/DegreeProgressLinks.js, src/react/components/_dashboard/UpNext/UpNextItem.js
https://jira-secure.berkeley.edu/browse/SISRP-48817
* Removes URL logging from Google Analytics link tracking
* Implements CS API Link logging convention
=> SISRP-48817 - Turn on What-if APR for Students - Google Analytics

app/models/campus_solutions/student_resources.rb
https://jira-secure.berkeley.edu/browse/SISRP-52832
=> SISRP-52832 - Fixed GT Eform Withdrawal form link

app/models/edo_oracle/financial_aid/queries.rb
https://jira-secure.berkeley.edu/browse/SISRP-52666
=> SISRP-52666 - Award Comparison fixes

src/assets/templates/widgets/enrollment/plan.html
https://jira-secure.berkeley.edu/browse/SISRP-52853
=> SISRP-52853 - Students not able to access Multi-Year Planner

app/models/textbooks/proxy.rb, spec/models/textbooks/proxy_spec.rb
https://jira-secure.berkeley.edu/browse/SISRP-52838
=> SISRP-52838 - Textbook Information Not Populating in CalCentral/Course Catalog

app/models/textbooks/proxy.rb, spec/models/textbooks/proxy_spec.rb
https://jira-secure.berkeley.edu/browse/SISRP-52838
See DEV PR #642
=> [QA] SISRP-52838 - Textbook Information Not Populating in CalCentral/Course Catalog

app/controllers/my_eft_enrollment_controller.rb, app/models/campus_solutions/message_catalog.rb, app/models/user/academics/class_info_message.rb, app/models/user/academics/enrollment_message.rb, app/models/user/academics/enrollment_term.rb, config/message_catalog.yml, config/routes.rb, spec/models/campus_solutions/message_catalog_spec.rb, src/assets/javascripts/angular/controllers/pages/academicsController.js, src/assets/javascripts/angular/factories/enrollmentFactory.js, src/assets/templates/academics_classinfo.html, src/react/components/ReadMore.js, src/react/components/_academics/ClassInfoNotice.js, src/react/components/_academics/EnrollmentNotice.module.scss, src/react/components/_academics/NoticeBox.js, src/react/components/angularWrappers/classInfoNotice.js, src/react/components/index.js
https://jira-secure.berkeley.edu/browse/SISRP-52454
=> SISRP-52454: Add callout box to Class Info Card

src/assets/templates/widgets/gear_popover.html
https://jira-secure.berkeley.edu/browse/SISRP-52965
=> SISRP-52965 - Cal Central Popover not displaying Status and Holds information

app/models/edo_oracle/financial_aid/queries.rb
https://jira-secure.berkeley.edu/browse/SISRP-47960
This reverts commit 7facbb48bb61a2a1825517760b52879e0a94ddc1.
=> Revert "SISRP-47960 - Adds Tuition and Fee Remissions disbursement dates to Awards Card"

src/assets/javascripts/angular/controllers/widgets/academics/graduateDegreeProgressController.js
https://jira-secure.berkeley.edu/browse/SISRP-52256
This reverts commit 5bf546e291c95bec2ce0fa2128f00a26d35ed1a2.
=> SISRP-52256 - Revert Changes - 2005 Previous Graduate Data showing in CalCentral for an active Law Student

src/assets/javascripts/angular/controllers/widgets/academics/graduateDegreeProgressController.js
https://jira-secure.berkeley.edu/browse/SISRP-52256
See DEV PR #654 
This reverts commit 5bf546e291c95bec2ce0fa2128f00a26d35ed1a2.
=> [QA] SISRP-52256 - Revert Changes 2005 Previous Graduate Data showing in CalCentral for an active Law Student

src/assets/templates/widgets/gear_popover.html
=> [QA] SISRP-52965 - Cal Central Popover not displaying Status and Holds information

app/models/edo_oracle/financial_aid/queries.rb
QA PR for #653 
This reverts commit 7facbb48bb61a2a1825517760b52879e0a94ddc1.
=> [QA] Revert "SISRP-47960 - Adds Tuition and Fee Remissions disbursement date to Awards Card"

src/assets/templates/widgets/enrollment/plan.html
https://jira-secure.berkeley.edu/browse/SISRP-52853
See DEV PR #645
=> [QA] SISRP-52853 - Students not able to access Multi-Year Planner

app/models/my_registrations/registrations_module.rb, app/models/user/academics/term_registration.rb
https://jira-secure.berkeley.edu/browse/SISRP-53041
=> SISRP-53041 - UGRD Students with S09 SIs and enrollment are not seeing the You are Subject to Cancel for Non-Payment Message in Status and Holds Card

src/react/components/_dashboard/COVIDResponseCard/COVIDResponseCard.js, src/react/components/_dashboard/COVIDResponseCard/COVIDResponseCard.module.scss, src/react/stylesheets/_colors.scss
https://jira-secure.berkeley.edu/browse/SISRP-53047
=> SISRP-53047: COVID Repsonse minor visual updates

src/react/components/_academics/StudentProfile/Degrees.js
SISRP-52689: CalCentral Law School Degree Display in Profile and Academic Summary (CLC Dev)
https://jira-secure.berkeley.edu/browse/SISRP-52689
=> SISRP-52689-CalCentral-Law-School-Degree-Display

src/assets/stylesheets/_academics.scss, src/assets/stylesheets/_alerts.scss, src/assets/stylesheets/_buttons.scss, src/assets/stylesheets/_enrollment_card.scss, src/assets/stylesheets/_finaid_compare_awards.scss, src/assets/stylesheets/_icons.scss, src/assets/stylesheets/_myfinances.scss, src/assets/stylesheets/_splash.scss, src/assets/stylesheets/_text.scss, src/assets/stylesheets/_toolbox.scss, src/assets/stylesheets/_useful.scss, src/assets/stylesheets/colors.scss, src/assets/templates/widgets/toolbox/user_preview.html, src/react/components/ButtonGroup.scss, src/react/components/Dropdown.scss, src/react/components/Tabs.scss, src/react/components/_dashboard/NotificationsCard/Tabs.module.scss, src/react/components/_dashboard/NotificationsCard/University/Unread.module.scss, src/react/components/_finances/AwardComparison/AwardComparison.scss, src/react/components/_finances/FinancialResources/FinancialResources.scss, src/react/components/_finances/TransactionsCard/BillingItem/ItemAdjustment.scss, src/react/components/_finances/TransactionsCard/BillingItemsTable/ShowMore.scss, src/react/stylesheets/_colors.scss, src/react/stylesheets/_foundation_overrides.scss, src/react/stylesheets/_variables.scss, src/react/stylesheets/icons.scss
https://jira-secure.berkeley.edu/browse/SISRP-52959
=> SISRP-52959 - Update Colors (Blue, Green, Yellow) in CalCentral

src/assets/templates/dashboard.html
https://jira-secure.berkeley.edu/browse/SISRP-53047
=> SISRP-53047: Don't use self-closing tag

app/models/edo_oracle/financial_aid/queries.rb
https://jira-secure.berkeley.edu/browse/SISRP-47960
=> SISRP-47960 - Display Est Disbursement Date on FA Award Card for Fee Remissions

app/models/edo_oracle/user_courses/section.rb, app/models/my_academics/grading/applicator.rb, spec/models/edo_oracle/user_courses/section_spec.rb
https://jira-secure.berkeley.edu/browse/SISRP-53231
=> SISRP-53231 - Grade Due Dates and Final Status columns in CalCentral Instructor Semester card not updating

src/react/components/_academics/ClassInformationCard/HorizontalClassAttributes.js, src/react/components/_academics/ClassInformationCard/VerticalClassAttributes.js
https://jira-secure.berkeley.edu/browse/SISRP-52459
=> SISRP-52459: Units don't need formatting

src/react/components/_academics/ClassInformationCard/ClassAttributesTable.js, src/react/components/_academics/ClassInformationCard/ClassAttributesTable.module.scss, src/react/components/_academics/ClassInformationCard/ClassInformationCard.js, src/react/components/_academics/ClassInformationCard/ClassNotesLink.js, src/react/components/_academics/ClassInformationCard/FinalExams.js, src/react/components/_academics/ClassInformationCard/FinalExams.module.scss, src/react/components/_academics/ClassInformationCard/HorizontalClassAttributes.js, src/react/components/_academics/ClassInformationCard/VerticalClassAttributes.js
https://jira-secure.berkeley.edu/browse/SISRP-52459
=> SISRP-52459: Class Information Card updates and fixes

app/models/textbooks/proxy.rb, config/settings.yml, spec/models/textbooks/proxy_spec.rb, src/assets/templates/textbook.html
https://jira-secure.berkeley.edu/browse/SISRP-52993
=> SISRP-52993 - Textbook API Base URL Change

src/react/components/_academics/Diploma/Diploma.js, src/react/components/_academics/Diploma/Diploma.scss
https://jira-secure.berkeley.edu/browse/SISRP-52274
=> SISRP-52774 - Style update. Open download link in new window

app/models/user/financial_aid/cached_award_comparison_data.rb, src/react/components/_academics/DegreeProgress/DegreeProgressLinks.scss, src/react/components/_finances/AwardComparison/Legend.js
https://jira-secure.berkeley.edu/browse/SISRP-53326
DEV PR: #687
=> [QA] SISRP-53326 - Fixes EFC on Award Comparison card (and minor style blemish)

app/models/hub_edos/student_api/v2/feeds/academic_statuses.rb
https://jira-secure.berkeley.edu/browse/SISRP-52274
=> SISRP-52274 - Add cacheing for iHub Student API v2 Academic Statuses

app/models/edo_oracle/user_courses/section.rb, app/models/my_academics/grading/applicator.rb, spec/models/edo_oracle/user_courses/section_spec.rb
https://jira-secure.berkeley.edu/browse/SISRP-53231
See Dev PR #680
=> [QA] SISRP-53231 - Grade Due Dates and Final Status columns in CalCentral Instructor Semester card not updating

app/models/user/finances/billing_item.rb, src/icons/due-now.svg, src/icons/due.svg, src/icons/exclamation-circle.svg, src/icons/not-due.svg, src/icons/not-yet-due.svg, src/icons/overdue.svg, src/react/components/_dashboard/NotificationsCard/University/Unread.module.scss, src/react/components/_finances/AwardComparison/AwardComparison.scss, src/react/components/_finances/TransactionsCard/Badges/Badges.scss, src/react/components/_finances/TransactionsCard/Badges/DueBadge.js, src/react/components/_finances/TransactionsCard/BillingItem/ChargeItem.js, src/react/components/_finances/TransactionsCard/BillingItem/ChargeStatus.js, src/react/stylesheets/_colors.scss, src/redux/reducers/BillingItemsReducer.js
https://jira-secure.berkeley.edu/browse/SISRP-51854
=> SISRP-51854: Fix missing status badges and update badge styles

app/models/textbooks/proxy.rb, config/settings.yml, spec/models/textbooks/proxy_spec.rb, src/assets/templates/textbook.html
https://jira-secure.berkeley.edu/browse/SISRP-52993
See Dev PR #689
=> [QA] SISRP-52993 - Textbook API Base URL Change

app/controllers/user/academics/diploma_controller.rb, app/models/hub_edos/student_api/v2/feeds/academic_statuses.rb, app/models/user/academics/diploma.rb
https://jira-secure.berkeley.edu/browse/SISRP-52274
=> SISRP-52274 - Remove cacheing for iHub Student API v2 Academic Statuses. Apply to User::Academics::Diploma

app/models/hub_edos/student_api/v2/feeds/academic_statuses.rb, app/models/user/academics/diploma.rb
https://jira-secure.berkeley.edu/browse/SISRP-52274
See DEV PR #698
=> [QA] SISRP-52274 - Remove cacheing for iHub Student API v2 Academic Statuses. Apply to User::Academics::Diploma

app/models/user/finances/billing_item.rb, src/icons/due-now.svg, src/icons/due.svg, src/icons/exclamation-circle.svg, src/icons/not-due.svg, src/icons/not-yet-due.svg, src/icons/overdue.svg, src/react/components/_dashboard/NotificationsCard/University/Unread.module.scss, src/react/components/_finances/AwardComparison/AwardComparison.scss, src/react/components/_finances/TransactionsCard/Badges/Badges.scss, src/react/components/_finances/TransactionsCard/Badges/DueBadge.js, src/react/components/_finances/TransactionsCard/BillingItem/ChargeItem.js, src/react/components/_finances/TransactionsCard/BillingItem/ChargeStatus.js, src/react/stylesheets/_colors.scss, src/redux/reducers/BillingItemsReducer.js
https://jira-secure.berkeley.edu/browse/SISRP-51854
See Dev PR #694
=> [QA] SISRP-51854: Fix missing status badges and update badge styles

app/models/campus_solutions/student_resources.rb, app/models/my_academics/class_enrollments.rb, src/assets/templates/widgets/enrollment/adjust_enrolled.html, src/react/components/_dashboard/StudentResources/StudentResources.js
https://jira-secure.berkeley.edu/browse/SISRP-53528
=> SISRP-53528 - Change Hard-coded Spring 2020 references in L&S Late Enrollment Action Form Link

app/models/campus_solutions/student_resources.rb, app/models/my_academics/class_enrollments.rb, src/assets/templates/widgets/enrollment/adjust_enrolled.html, src/react/components/_dashboard/StudentResources/StudentResources.js
https://jira-secure.berkeley.edu/browse/SISRP-53528
See DEV PR #704
=> [QA] SISRP-53528 - Change Hard-coded Spring 2020 references in L&S Late Enrollment Action Form Link

src/assets/javascripts/angular/directives/academicSectionIncompleteGradingStatus.js, src/assets/stylesheets/_academic_plan.scss, src/assets/templates/academics_final_grades.html, src/assets/templates/academics_semesters.html, src/assets/templates/directives/academic_section_incomplete_grading_status.html, src/assets/templates/widgets/academic_plan.html, src/react/components/_academics/AcademicSummary/LawSection.js, src/react/components/_academics/AcademicSummary/PrimarySection.js, src/react/components/_academics/AcademicSummary/SectionIncompleteGradingStatus.js, src/react/components/_academics/TransferCredit/GenericTransferCredit.js, webpack.config.js
=> SISRP-53626 - Update Hard-Coded “Lapse Date” Language in CalCentral

src/assets/javascripts/angular/directives/academicSectionIncompleteGradingStatus.js, src/assets/stylesheets/_academic_plan.scss, src/assets/templates/academics_final_grades.html, src/assets/templates/academics_semesters.html, src/assets/templates/directives/academic_section_incomplete_grading_status.html, src/assets/templates/widgets/academic_plan.html, src/react/components/_academics/AcademicSummary/LawSection.js, src/react/components/_academics/AcademicSummary/PrimarySection.js, src/react/components/_academics/AcademicSummary/SectionIncompleteGradingStatus.js, src/react/components/_academics/TransferCredit/GenericTransferCredit.js, webpack.config.js
=> [QA] SISRP-53626 - Update Hard-Coded “Lapse Date” Language in CalCentral

src/assets/templates/academics.html
https://jira-secure.berkeley.edu/browse/SISRP-53697
=> SISRP-53697 - Remove access to Law Degree Progress Card for Concurrent, Joint and Inactive Students (JD)

src/assets/javascripts/angular/directives/academicSectionIncompleteGradingStatus.js, src/assets/templates/academics_final_grades.html, src/assets/templates/academics_semesters.html, src/assets/templates/directives/academic_section_incomplete_grading_status.html, src/assets/templates/widgets/academic_plan.html
=> SISRP-53626 - Fix academicSectionIncompleteGradingStatus directive and attribute passing

src/assets/javascripts/angular/directives/academicSectionIncompleteGradingStatus.js, src/assets/templates/academics_final_grades.html, src/assets/templates/academics_semesters.html, src/assets/templates/directives/academic_section_incomplete_grading_status.html, src/assets/templates/widgets/academic_plan.html
=> [QA] SISRP-53626 - Fix academicSectionIncompleteGradingStatus directive and attribute passing

src/assets/javascripts/angular/directives/academicSectionIncompleteGradingStatus.js, src/assets/templates/academics_final_grades.html, src/assets/templates/academics_semesters.html, src/assets/templates/directives/academic_section_incomplete_grading_status.html, src/assets/templates/widgets/academic_plan.html
=> SISRP-53626 - Fixes issue with section values not passing by value with isolated scope directive

src/assets/javascripts/angular/directives/academicSectionIncompleteGradingStatus.js, src/assets/templates/academics_final_grades.html, src/assets/templates/academics_semesters.html, src/assets/templates/directives/academic_section_incomplete_grading_status.html, src/assets/templates/widgets/academic_plan.html
=> [QA] SISRP-53626 - Fixes issue with section values not passing by value with isolated scope directive

src/assets/templates/academics.html
https://jira-secure.berkeley.edu/browse/SISRP-53697
QA PR for #713
=> [QA] SISRP-53697 - Remove access to Law Degree Progress Card for Concurrent, Joint and Inactive Students (JD)

app/models/hub_edos/classes_api/v1/sections.rb, spec/models/hub_edos/classes_api/v1/section_spec.rb, spec/models/hub_edos/classes_api/v1/sections_spec.rb
https://jira-secure.berkeley.edu/browse/SISRP-53779
=> SISRP-53779 - Fix Hub Class Sections API when 404 response returned

app/models/enf/handler.rb, app/models/enf/message.rb, app/models/user/cards/enrollment_expiry.rb, app/models/user/notifications/expiry.rb, app/models/user/tasks/expiry.rb, spec/models/enf/message_spec.rb, spec/models/enf/processor_spec.rb
https://jira-secure.berkeley.edu/browse/SISRP-53539
See DEV PR #707
=> [QA] SISRP-53539: Allow ENF::Handler classes to work with any existing ENF payload format

src/react/components/_academics/StudentProfile/Degrees.js
https://jira-secure.berkeley.edu/browse/SISRP-52689
Reverting work to keep it from going into 10/04 release or thereafter.
=> SISRP-52689 - Reverting work

app/models/user/academics/berkeley_time.rb, app/models/user/academics/enrollment_career.rb, app/models/user/academics/enrollment_period.rb
https://jira-secure.berkeley.edu/browse/SISRP-53691
=> SISRP-53691: Output enrollment datetimes with TZ info for correct parsing

src/assets/templates/widgets/profile/delegate.html
https://jira-secure.berkeley.edu/browse/SISRP-53391
=> SISRP-53391 - Delegate Access replace with API link

app/models/my_classes/campus.rb
https://jira-secure.berkeley.edu/browse/SISRP-53850
=> SISRP-53850 - FATAL errors in the CalCentral logs with a HTTP 500

src/assets/templates/widgets/enrollment/explore.html
https://jira-secure.berkeley.edu/browse/SISRP-53876
=> SISRP-53876 - Wrong URL for Class Textbooks: ASUC Bookstore link on the Class Enrollment card

src/assets/templates/widgets/profile/delegate.html
=> [QA] SISRP-53391 - Delegate Access replace with API link

app/models/user/academics/berkeley_time.rb, app/models/user/academics/enrollment_career.rb, app/models/user/academics/enrollment_period.rb
https://jira-secure.berkeley.edu/browse/SISRP-53691
See DEV PR #729
=> [QA] SISRP-53691: Output enrollment datetimes with TZ info for correct parsing

app/models/my_classes/campus.rb
=> [QA] SISRP-53850 - FATAL errors in the CalCentral logs with a HTTP 500

app/models/hub_edos/student_api/v2/student/academic_status.rb, spec/models/hub_edos/student_api/v2/student/academic_status_spec.rb
https://jira-secure.berkeley.edu/browse/SISRP-53913
=> SISRP-53913 - CeDiploma Not Displaying for Student

src/react/components/index.js
https://jira-secure.berkeley.edu/browse/SISRP-53943
=> SISRP-53943 - Re-Add Transfer Credit Text to Degree Requirements Card

public/json/campuslinks.json
https://jira-secure.berkeley.edu/browse/SISRP-52577
=> SISRP-52660 - Update broken links in My Campus pages

src/react/components/index.js
https://jira-secure.berkeley.edu/browse/SISRP-53943
See DEV PR #743
=> [QA] SISRP-53943 - Re-Add Transfer Credit Text to Degree Requirements Card

app/models/campus_solutions/student_resources.rb, spec/models/campus_solutions/student_resources_spec.rb
=> [QA] SISRP-53398 - Grad Div Change of Class Schedule

app/models/user/finances/billing_summary.rb
https://jira-secure.berkeley.edu/browse/SISRP-53398
=> SISRP-53676 - Update CLC Billing Transactions CSV Download

app/models/hub_edos/student_api/v2/student/academic_status.rb, spec/models/hub_edos/student_api/v2/student/academic_status_spec.rb
https://jira-secure.berkeley.edu/browse/SISRP-53913
See DEV PR #741
=> [QA] SISRP-53913 - CeDiploma Not Displaying for Student

app/models/user/finances/billing_summary.rb
=> [QA] SISRP-53676 - Update CLC Billing Transactions CSV Download

script/install-jars.sh
https://jira-secure.berkeley.edu/browse/SISRP-52172
=> SISRP-52172 - Update Warfile packaging to prefer inclusion of ojdbc8.jar over ojdbc7.jar

script/install-jars.sh
https://jira-secure.berkeley.edu/browse/SISRP-52172
See DEV PR #754
=> [QA] SISRP-52172 - Update Warfile packaging to prefer inclusion of ojdbc8.jar over ojdbc7.jar

app/models/concerns/loan_history_module.rb, spec/models/concerns/loan_history_module_spec.rb
https://jira-secure.berkeley.edu/browse/SISRP-54017
See DEV PR #752
=> [QA] SISRP-54017 - CLC: Divide by Zero error causing error with FA Loan History card

config/settings/development.yml
https://jira-secure.berkeley.edu/browse/SISRP-52172
See DEV PR #758
=> [QA] SISRP-52172 - Configures 'oracle_enhanced' as default EDODB adapter for local development

app/models/alumni_profile.rb, app/models/api/alumni_profiles.rb, spec/models/api/alumni_profiles_spec.rb, src/index.html
https://jira-secure.berkeley.edu/browse/SISRP-52605
* this has the fix for the don't show again checkbox
=> SISRP-52605 - Entry Into Alum/ Former Portal

app/models/api/service_alerts.rb
https://jira-secure.berkeley.edu/browse/SISRP-43007
=> SISRP-43007: Fix splash feed cache expiry

app/models/api/service_alerts.rb
https://jira-secure.berkeley.edu/browse/SISRP-43007
See DEV PR #770
=> [QA] SISRP-43007: Fix splash feed cache expiry

src/react/components/_finances/TransactionsCard/TransactionsCardContainer.js
PR: https://jira-secure.berkeley.edu/browse/SISRP-54248
=> SISRP-54248: Restore transactions card container

src/react/components/_finances/TransactionsCard/TransactionsCardContainer.js
https://jira-secure.berkeley.edu/browse/SISRP-54248
See DEV PR #773
=> [QA] SISRP-54248: Restore transactions card container

app/models/edo_oracle/queries.rb
https://jira-secure.berkeley.edu/browse/SISRP-54254
=> SISRP-54254 - Optimize PNP Unit count query

src/components/AlertBar.js
https://jira-secure.berkeley.edu/browse/SISRP-54291
=> SISRP-54291: hide AlertBar if splash_only

src/react/angularWrappers/NgActiveServiceAlerts.js
https://jira-secure.berkeley.edu/browse/SISRP-54290
=> SISRP-54290: Only show ActiveServiceAlerts to those with permission

app/models/berkeley/term.rb, app/models/berkeley/terms.rb, app/models/campus_solutions/sir/sir_statuses.rb, app/models/concerns/transfer_credit.rb, app/models/financial_aid/my_housing.rb, app/models/google_apps/auth/authorization.rb, app/models/my_academics/class_enrollments.rb, app/models/my_academics/grading/applicator.rb, app/models/my_academics/grading/helpers.rb, app/models/my_academics/grading/period.rb, app/models/my_registrations/flagged_terms.rb, app/models/my_tasks/sis_tasks.rb, app/models/my_tasks/tasks_module.rb, app/models/user/academics/term.rb, app/models/user/api.rb, app/models/user/finances/billing_item.rb, app/models/user/finances/billing_summary.rb, lib/cache/cacheable_date_time.rb, lib/csv_export.rb, spec/lib/cache/cacheable_date_time_spec.rb
https://jira-secure.berkeley.edu/browse/SISRP-54265
This is based on ets-berkeley-edu/calcentral#7829
We should revert this if it's fixed in jRuby v9.2.14.0
=> SISRP-54265 - Address "invalid offset is ignored" error

src/react/components/_academics/EnrollmentAppointments/LawEnrollmentAppointments.js
https://jira-secure.berkeley.edu/browse/SISRP-54312
=> SISRP-54312 - LAW Only: Wrong Date/Time Shown for Enrollment Information

app/models/berkeley/term.rb, app/models/berkeley/terms.rb, app/models/campus_solutions/sir/sir_statuses.rb, app/models/concerns/transfer_credit.rb, app/models/financial_aid/my_housing.rb, app/models/google_apps/auth/authorization.rb, app/models/my_academics/class_enrollments.rb, app/models/my_academics/grading/applicator.rb, app/models/my_academics/grading/helpers.rb, app/models/my_academics/grading/period.rb, app/models/my_registrations/flagged_terms.rb, app/models/my_tasks/sis_tasks.rb, app/models/my_tasks/tasks_module.rb, app/models/user/academics/term.rb, app/models/user/api.rb, app/models/user/finances/billing_item.rb, app/models/user/finances/billing_summary.rb, lib/cache/cacheable_date_time.rb, lib/csv_export.rb, spec/lib/cache/cacheable_date_time_spec.rb
https://jira-secure.berkeley.edu/browse/SISRP-54265
See DEV PR #776
=> [QA] SISRP-54265 - Address "invalid offset is ignored" error

src/react/components/_academics/EnrollmentAppointments/LawEnrollmentAppointments.js
https://jira-secure.berkeley.edu/browse/SISRP-54312
See DEV PR #779
=> [QA] SISRP-54312 - LAW Only: Wrong Date/Time Shown for Enrollment Information
