app/models/campus_solutions/student_resources.rb
spec/models/campus_solutions/student_resources_spec.rb

https://jira.berkeley.edu/browse/SISRP-45460
`MyAcademics::MyAcademicRoles.new(@uid).get_feed` returns an object that mixes symbol and string keys, like so:
```
:feed => {
:current => {
"law" => true,
"grad" => true
}
}
```
This fixes the `CampusSolutions::StudentResources` model, which was previously using symbol keys for everything. I'm also going to open a JIRA ticket to symbolize all the keys for the object, as I'm sure this will lead to more bugs in the future if we leave the object keys as a mix of symbols and strings.

SISRP-45460 - Remove eform Links from Student Resources Card for Law Students

---

spec/models/calnet_ldap/user_attributes_spec.rb

First test is for conflicts between student ID and Campus Solutions ID (Line 73-75 of model), checks that expected warning is logged
Second test is for null response

[CalCentral A] user_attributes_spec.rb

---

spec/models/edo_oracle/career_spec.rb

Tests added and improved by Rishab Srivastava and Samir Naqvi. CS 169, CalCentral A.
- Created two tests for `get_cumulative_units`, and check expected results for User IDs 300216, 790833
- Added one additional test for `fetch` by adding an additional User ID 300216

[CalCentral A] career_spec.rb

---

spec/models/canvas/account_roles_spec.rb

- Added an intermediate test to check that the 'defined_course_roles' method returns an output when given a proper academic department sub-account or projects site account ID as input.
- Added a test to ensure proper handling of invalid student.
Tests added and improved by Srujay Korlakunta and Andrew Wan.

[CalCentral A] account_roles_spec.rb

---

spec/models/edo_oracle/course_sections_spec.rb

- Added new test that checks that getting section data does not unexpectedly create new schedules given no meeting times or without a list of instructors.
Tests added and improved by Srujay Korlakunta and Andrew Wan.

[CalCentral A] course_sections_spec.rb

---

spec/models/edo_oracle/user_courses/base_spec.rb

Tests added and improved by Sayan Ray Chaudhuri. CS 169, CalCentral A.
In the base_spec.rb test,
1. When testing row to feed item, added check for when both course title and course title short are nil.
2. For get section grading, added test for when grading basis is not present, regardless of primary section.

[CalCentral A] base_spec.rb

---

spec/models/cal_groups/group_save_spec.rb

Tests added and improved by Andrew Wan and Srujay Korlakunta. CS 169, CalCentral A.
In the group_save_spec.rb test, 
1. Verifies that the correct group data is returned after saving.
2. Added a test to check that if the save action fails, no group is incorrectly returned.

[CalCentral A] group_save_spec.rb

---

spec/models/cal_groups/find_groups_spec.rb

Tests added and improved by Moses Kim. CS 169, CalCentral A.
- Created a test to check that the raised error for an unsuccessful CalGroups response is of the correct type (`Errors:ProxyError`) and log message
- Extracted test for error behavior into `'unexpected response'` shared example
Note: the `successful?(response) && response['WsFindGroupsResults']` condition of `find_groups.rb` (Line 22) may be redundant, as `successful?(response)` raises an error through `results_metadata` when `response['WsFindGroupsResults']` is `nil`. Another test for a successful but malformed response may be necessary.

[CalCentral A] find_groups_spec.rb

---

app/models/hub_edos/student.rb
spec/models/hub_edos/student_spec.rb

https://jira.berkeley.edu/browse/SISRP-39356
https://jira-secure.berkeley.edu/browse/SISRP-39356
Students that are no longer active (discontinued, dismissed, or completed) are not able to see their academic level when they should. This switches to an algorithm that identifies the "latest" term (highest one in a sorted list) and grabs the academic levels for that term. Most cases have a single academic level, but a dual career student (GRAD + LAW) might have two level descriptions that need to be displayed.

SISRP-39356 - Updates HubEdos::Student to return academic levels based on latest term registrations

---

app/models/financials/proxy.rb
config/settings.yml

https://jira-secure.berkeley.edu/browse/SISRP-46673
This API only has the single end-point for the student, so I don't think we need to keep the base_url short. I'm moving it all to the proxy configuration so that no matter what the URL ends up being, we'll be able to modify the configuration rather than the code.

SISRP-46673 - Updates API request path in Financials proxy

---

app/models/financial_aid/my_financial_aid_summary.rb
fixtures/xml/campus_solutions/link_api_multiple.xml
spec/models/financial_aid/my_financial_aid_summary_spec.rb
src/assets/templates/widgets/finaid_summary_footer.html

https://jira-secure.berkeley.edu/browse/SISRP-45286
Note - we intend to make the CS Link API value "Inactive" so that this link does not show to the student until the dependent CS work is complete.

SISRP-45286 - Adds FA Transcript link to FA Summary card

---

package-lock.json

Updates the `package-lock.json` file to allow dependency requirements to include semantic versioning.
See [tilde and caret get added package-log.json in v6 but not in v5](https://github.com/npm/npm/issues/20891)

NOJIRA - Update package-lock.json syntax to allow sem-version for requirements/dependencies

---

src/react/components/_academics/AcademicSummary/SectionIncompleteGradingStatus.js

https://jira-secure.berkeley.edu/browse/SISRP-46531
Updates component to only render a table row when applicable to display. This should resolve the issue with "spacing" between classes pointed out by Marty Sulc.

SISRP-46531 - Omits row when lapse date or frozen grade status not displayed

---

src/react/components/_academics/StatusAndHoldsCard/CNPWarning.js
src/react/components/_academics/StatusAndHoldsCard/RegistrationPeriod.js

The flag for Cancel-For-Non-Payment should be hasCNPWarning, not showCnp. In addition, CNP warning should come before registration status message.

SISRP-47626-Missing-Cancel-For-Non-Payment

---

app/models/financial_aid/my_finaid_profile.rb
spec/models/financial_aid/my_finaid_profile_spec.rb

https://jira-secure.berkeley.edu/browse/SISRP-47655

SISRP-47655 - hides Academic Holds from Finaid Profile card when 0

---

app/models/financial_aid/my_finaid_profile.rb
spec/models/financial_aid/my_finaid_profile_spec.rb

https://jira-secure.berkeley.edu/browse/SISRP-47655

[QA] SISRP-47655 - hides Academic Holds from Finaid Profile card when 0

---

script/sis/verify_sis_api_endpoints.sh

Inspired by https://jira-secure.berkeley.edu/browse/SISRP-22974
API usage was deprecated in #6977. See removed `holds.rb`.

NOJIRA - Remove deprecated CS API UC_CC_SERVC_IND.v1 leftover from SISRP-37719

---

app/models/hub_edos/student_api/v2/academic_statuses.rb

https://jira-secure.berkeley.edu/browse/SISRP-48319
Related to changes made in [SISRP-46907](https://jira-secure.berkeley.edu/browse/SISRP-46907). It's querying too much information, as compared to Student API V1 (which didn't include completed or inactive career/plan data)

SISRP-48319 - Undergrad GPA and Career Showing for Law Student

---

config/settings.yml

https://jira-secure.berkeley.edu/browse/SISRP-46050
MyAcademics::Merged relies on iHub data from MyAcademicsStatus data. Need GPA data to line up with grading data. Setting both to expire after 15 minutes.

SISRP-46050 - Sets MyAcademics::MyAcademicsStatus to use 15 minute cache expiration

---

app/models/user/academics/status/undergraduate.rb

https://jira-secure.berkeley.edu/browse/SISRP-46547

SISRP-46547 Et al.: Only show undergrad reg status in popover if warning

---

app/models/my_academics/semesters.rb

https://jira-secure.berkeley.edu/browse/SISRP-48567
This was a very silly thing that happened that was hard to diagnose. The MyAcademics::Semesters class was deleting items from an array, and this was going all the way back to the cached data returned by `EdoOracle::UserCourses::All#all_campus_courses`. Because MyAcademics::Teaching relies on the same data, no instructor courses were showing because the non-student courses were all deleted in MyAcademics::Semester.
This fix resolves that.

SISRP-48567 - My Academics Page is missing instructor assignments for faculty

---

script/front-end-build.sh

Allows us to make a clear distinction between libraries the app uses and those required for local development, building, linting, etc. by allowing our build server access everything.

NOJIRA: Allow build server access to devDependencies

---

app/models/degree_progress/my_undergrad_requirements.rb
spec/models/degree_progress/my_undergrad_requirements_spec.rb

https://jira-secure.berkeley.edu/browse/SISRP-48130
* fix edge case of missing statuses for advisors 
* added more unit tests to cover edge cases

SISRP-48130 - Allow APR Link to Remain Active after Students' Last Day of Term for Expected Grad Term

---

README.md

I was using a version of node installed by Homebrew. This isn't recommended. We should be using NVM so that we're using the version specified by `.nvmrc`.

NOJIRA - Update README with NVM install instructions

---

app/models/campus_solutions/sir/sir_statuses.rb

SISRP-46663 Confirming Deposit Waivers, before and after SIR (CLC DEV)
@redconfetti, Instead of mapping origDepositDue to "Waived", I decided to pass the origDepositDue to the HTML/angular code. It gives the front end the flexibility to show different messages depending on the amount, in case the business requirement changes in the future.

SISRP-46663 pass the original deposit due to the html/angular

---

config/settings.yml

https://jira-secure.berkeley.edu/browse/SISRP-51360
The Graduate Higher Degree Commmittees card relies on conversion of EMPLID to UID for each committee member. We're cacheing the results of the Crosswalk lookup, but only for 35 minutes. We're cacheing the opposite lookup (UID to EMPLID) for 4 hours, so I don't see why it wouldn't be appropriate to cache the reverse lookup for 4 hours also.

SISRP-51360 - Higher Degree Committees card is taking long time to load

---

src/assets/templates/widgets/student_success/finances.html
src/assets/templates/widgets/student_success/gpa_trends.html
src/assets/templates/widgets/student_success/student_success.html
src/assets/templates/widgets/student_success/units.html

https://jira-secure.berkeley.edu/browse/SISRP-51542
This is the first task where we are adding IDs and Classes to a card so that the QA team can better configure their test automation suite.
After a discussion with Janhavi, we determined we should use the `$index` value in the `id` attribute when iterating over arrays to render a collection of elements. She clarified that it's not practical to assert against table row that is specific to a term.
This is because students become expired (no longer able to log into CalCentral), so they have to put a new student ID in. Each student has variable term specific data. At most they would want to assert that 2 term rows are expected, so they'd want to assert something like `row[0]` and `row[1]` are present.
So this is why we want to use the `index` …

SISRP-51542 - Create unique ids for Term Table on Student Success Card for Test Automation

---

src/assets/templates/widgets/toolbox/user_preview.html

https://jira-secure.berkeley.edu/browse/SISRP-50112
Create link from Student Overview page in CalCentral to BOA (CLC dev)
should pass UID, not student ID to BOA (Berkeley Online Adivising)

SISRP-50112: Create link from Student Overview page in CalCentral to BOA

---

app/models/berkeley/grade_options.rb

https://jira-secure.berkeley.edu/browse/SISRP-51938

SISRP-51938 - Instructors cannot see Grade Basis and Units in Class Roster

---

app/models/berkeley/grade_options.rb

https://jira-secure.berkeley.edu/browse/SISRP-51938
See DEV PR #559

[QA] SISRP-51938 - Instructors cannot see Grade Basis and Units in Class Roster

---

app/models/user/academics/term_registration.rb

https://jira-secure.berkeley.edu/browse/SISRP-53041
I could not easily access the registrations from the model directly so I had to call cached feed and parse json, ugly but at least cnp logic in unified. This whole thing needs to be refactored and the registration_module retired

SISRP-53041 - UGRD Students with S09 SIs and enrollment are not seeing the You are Subject to Cancel for Non-Payment Message in Status and Holds Card

---

src/react/components/_academics/ClassInformationCard/ClassAttributesTable.js
src/react/components/_academics/ClassInformationCard/ClassInformationCard.js

https://jira-secure.berkeley.edu/browse/SISRP-52459
`teachingSemesters` don't have the `isLaw` attribute, but they share the `courseCareerCode` with regular student semesters

SISRP-52459: Fix class notes link displaying for law instructors

---

app/models/enf/handler.rb
app/models/enf/message.rb
app/models/user/cards/enrollment_expiry.rb
app/models/user/notifications/expiry.rb
app/models/user/tasks/expiry.rb
spec/models/enf/message_spec.rb
spec/models/enf/processor_spec.rb

https://jira-secure.berkeley.edu/browse/SISRP-53539

SISRP-53539: Allow ENF::Handler classes to work with any existing ENF payload format

---

app/models/concerns/loan_history_module.rb
spec/models/concerns/loan_history_module_spec.rb

https://jira-secure.berkeley.edu/browse/SISRP-54017

SISRP-54017 - CLC: Divide by Zero error causing error with FA Loan History card
